# Generated by Django 5.2.7 on 2025-12-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_remove_concoursmodel_concours_corps_i_871a7f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concoursmodel',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
