# Generated by Django 5.2.7 on 2025-12-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_alter_concoursmodel_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('titre', models.CharField(max_length=500)),
                ('profile', models.TextField()),
                ('category', models.CharField(blank=True, max_length=10, null=True)),
                ('verse', models.CharField(blank=True, max_length=10, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('limit_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'db_table': 'offers',
            },
        ),
        migrations.AlterField(
            model_name='vectorizeddocumentmodel',
            name='document_type',
            field=models.CharField(choices=[('CORPS', 'CORPS'), ('GRADE', 'GRADE'), ('CONCOURS', 'CONCOURS'), ('CONCOURS_LAW', 'CONCOURS_LAW'), ('CONCOURS_LAW_DETAILS', 'CONCOURS_LAW_DETAILS'), ('OFFER', 'OFFER')], db_index=True, max_length=20),
        ),
    ]
