# Generated by Django 5.2.7 on 2025-11-19 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_rawdocument_rename_rawexamination_legifranceconcours_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegifranceConcours',
        ),
    ]
