# Generated by Django 5.2.7 on 2025-12-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_delete_legifranceconcours'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpsModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=10)),
                ('ministry', models.CharField(max_length=100)),
                ('diploma_level', models.IntegerField(blank=True, null=True)),
                ('short_label', models.CharField(max_length=200)),
                ('long_label', models.TextField()),
                ('access_modalities', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Corps',
                'verbose_name_plural': 'Corps',
                'db_table': 'corps',
            },
        ),
    ]
