# Generated by Django 5.2.7 on 2025-12-03 16:10

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0006_corpsmodel'),
    ]

    operations = []
