# Generated by Django 5.2.7 on 2025-12-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0008_alter_corpsmodel_category'),
    ]

    operations = []
