# Generated by Django 5.2.7 on 2026-01-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion","0014_alter_rawdocument_document_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rawdocument",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="rawdocument",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CORPS", "CORPS"),
                    ("GRADE", "GRADE"),
                    ("CONCOURS", "CONCOURS"),
                    ("CONCOURS_LAW", "CONCOURS_LAW"),
                    ("CONCOURS_LAW_DETAILS", "CONCOURS_LAW_DETAILS"),
                    ("OFFERS", "OFFERS"),
                ],
                max_length=25,
                null=True,
                verbose_name="Type de document",
            ),
        ),
        migrations.AddConstraint(
            model_name="rawdocument",
            constraint=models.UniqueConstraint(
                fields=("external_id", "document_type"),
                name="unique_external_id_document_type",
            ),
        ),
    ]
