# Generated by Django 6.0.2 on 2026-02-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0016_convert_document_id_to_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawdocument",
            name="error_msg",
            field=models.TextField(blank=True, null=True),
        ),
    ]
