# Generated by Django 6.0.2 on 2026-02-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0017_rawdocument_error_msg"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawdocument",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
