# Generated by Django 6.0.5 on 2026-05-28 15:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0023_alter_source_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcemodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='source_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
