# Generated by Django 6.0.6 on 2026-06-12 13:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0027_apilogdailyaggregationmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcemodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sourcemodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="sourcemodel",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
