# Generated by Django 6.0.6 on 2026-06-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0030_sourcemodel_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcemodel",
            name="type",
            field=models.CharField(
                choices=[("talentsoft", "talentsoft"), ("api", "api")], max_length=50
            ),
        ),
    ]
