# Generated by Django 6.0.6 on 2026-06-23 13:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0031_alter_sourcemodel_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcemodel",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
