# Generated by Django 6.0.6 on 2026-06-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0032_alter_sourcemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcemodel',
            name='base_url_back',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='base_url_front',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='client_id_back',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='client_id_front',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
