# Generated by Django 6.1.1 on 2026-09-21 12:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0033_alter_source_optional_api_fields'),
        ('recruteur', '0013_merge_20260915_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentsoftOrganismeModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('entity_code', models.CharField(max_length=50, unique=True)),
                ('parent_code', models.IntegerField(blank=True, null=True)),
                ('has_children', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('post_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('max_delay_for_consent', models.IntegerField(blank=True, null=True)),
                ('retention_period', models.IntegerField(blank=True, null=True)),
                ('general_conditions', models.TextField(blank=True, null=True)),
                ('personal_data_consent', models.TextField(blank=True, null=True)),
                ('organisme', models.ForeignKey(db_column='organisme_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='talentsoft_organismes', to='recruteur.organismemodel')),
            ],
            options={
                'verbose_name': 'Organisme Talentsoft',
                'verbose_name_plural': 'Organismes Talentsoft',
                'db_table': 'talentsoft_organisme',
            },
        ),
    ]
