# Generated by Django 6.1.1 on 2026-09-22 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0034_talentsoftorganismemodel'),
        ('recruteur', '0013_merge_20260915_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentsoftorganismemodel',
            name='organisme',
            field=models.ForeignKey(blank=True, db_column='organisme_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talentsoft_organismes', to='recruteur.organismemodel'),
        ),
    ]
