# Generated by Django 5.2.7 on 2025-11-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nor', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='Code NOR')),
                ('legitext_id', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='LEGITEXT ID')),
                ('law_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Numéro de Décret ou Arrêté ou Code')),
                ('nature', models.CharField(blank=True, choices=[('DECREE', 'Decree'), ('ORDER', 'Order'), ('LAW', 'Law')], max_length=10, null=True, verbose_name='Nature de la Loi')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Titre du texte')),
                ('publication_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('state', models.CharField(blank=True, choices=[('EFFECTIVE', 'Effective'), ('REPEALED', 'Repealed')], max_length=10, null=True, verbose_name='Etat du texte')),
                ('raw_content', models.JSONField(blank=True, null=True, verbose_name='Contenu brut du texte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Examen brut',
                'verbose_name_plural': 'Examens bruts',
                'ordering': ['-created_at'],
            },
        ),
    ]
