# Generated by Django 5.2.7 on 2025-11-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_delete_legifranceconcours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdocument',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
