# Generated by Django 5.2.7 on 2025-12-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0009_vectorizeddocumentmodel_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdocument',
            name='document_type',
            field=models.CharField(blank=True, choices=[('CORPS', 'CORPS'), ('GRADE', 'GRADE'), ('CONCOURS', 'CONCOURS'), ('CONCOURS_LAW', 'CONCOURS_LAW'), ('CONCOURS_LAW_DETAILS', 'CONCOURS_LAW_DETAILS')], max_length=25, null=True, verbose_name='Type de document'),
        ),
        migrations.AlterField(
            model_name='vectorizeddocumentmodel',
            name='document_type',
            field=models.CharField(choices=[('CORPS', 'CORPS'), ('GRADE', 'GRADE'), ('CONCOURS', 'CONCOURS'), ('CONCOURS_LAW', 'CONCOURS_LAW'), ('CONCOURS_LAW_DETAILS', 'CONCOURS_LAW_DETAILS')], db_index=True, max_length=20),
        ),
    ]
