# Generated by Django 5.2.7 on 2025-12-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0010_alter_rawdocument_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdocument',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='NOR pour CONCOURS, corps_id pour CORPS', max_length=255, null=True, verbose_name='Identifiant externe'),
        ),
        migrations.AlterUniqueTogether(
            name='rawdocument',
            unique_together={('external_id', 'document_type')},
        ),
    ]
