# Generated by Django 5.2.7 on 2025-12-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0013_delete_corpsmodel_delete_vectorizeddocumentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdocument',
            name='document_type',
            field=models.CharField(blank=True, choices=[('CORPS', 'CORPS'), ('GRADE', 'GRADE'), ('CONCOURS', 'CONCOURS'), ('CONCOURS_LAW', 'CONCOURS_LAW'), ('CONCOURS_LAW_DETAILS', 'CONCOURS_LAW_DETAILS'), ('OFFER', 'OFFER')], max_length=25, null=True, verbose_name='Type de document'),
        ),
    ]
