# Generated by Django 5.2.7 on 2026-01-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0004_create_offers_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offermodel",
            old_name="titre",
            new_name="title",
        ),
    ]
