# Generated by Django 5.2.10 on 2026-01-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0005_rename_titre_to_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offermodel",
            old_name="limit_date",
            new_name="beginning_date",
        ),
        migrations.AddField(
            model_name="offermodel",
            name="contract_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TITULAIRE_CONTRACTUEL", "TITULAIRE_CONTRACTUEL"),
                    ("CONTRACTUELS", "CONTRACTUELS"),
                    ("TERRITORIAL", "TERRITORIAL"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="offermodel",
            name="country",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="offermodel",
            name="mission",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="offermodel",
            name="offer_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="offermodel",
            name="organization",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="offermodel",
            name="publication_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="offermodel",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("APLUS", "APLUS"),
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("HORS_CATEGORIE", "HORS_CATEGORIE"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="offermodel",
            name="department",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="offermodel",
            name="region",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="offermodel",
            name="verse",
            field=models.CharField(
                choices=[("FPT", "FPT"), ("FPE", "FPE"), ("FPH", "FPH")], max_length=20
            ),
        ),
    ]
