# Generated by Django 5.2.10 on 2026-01-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0007_remove_default_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offermodel",
            name="publication_date",
            field=models.DateTimeField(default="2024-01-01T00:00:00Z"),
        ),
    ]
