# Generated by Django 5.2.10 on 2026-01-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0008_make_publication_date_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offermodel",
            name="publication_date",
            field=models.DateTimeField(),
        ),
    ]
