# Generated by Django 6.0.4 on 2026-04-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0021_update_metiers_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metiermodel",
            name="competences",
        ),
    ]
