from typing import Protocol

from domain.value_objects.source import Source


class ISourcesRepository(Protocol):
    def load(self, sources: list[Source]) -> None: ...
    def get_by_client_id_back(self, client_id_back: str) -> Source | None: ...
    def get_by_source_id(self, source_id: str) -> Source | None: ...
    def __len__(self) -> int: ...
