# Generated by Django 5.2.7 on 2025-11-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawCorps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(verbose_name='Contenu brut Ingres')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RawCorps',
                'verbose_name_plural': 'RawCorps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='rawexamination',
            options={'ordering': ['-created_at'], 'verbose_name': 'RawExamination', 'verbose_name_plural': 'RawExaminations'},
        ),
    ]
