// Source éditoriale : faq-v1.md (tenue hors dépôt) ; une modification ici doit être reportée dans la source.
import type { FaqEntree } from '../types'

export const FAQ_THEMES = [
  'Démarrer',
  'Candidatures',
  'Étapes',
  'Recrutements',
  'Organisme et équipe',
  'Notes, documents, messages',
  'Droits et rôles',
  'Problèmes courants',
] as const

export const FAQ_ENTREES = [
  {
    id: 'dem-aucun-recrutement',
    theme: 'Démarrer',
    question: 'Je viens de me connecter et je ne vois aucun recrutement : est-ce normal ?',
    reponse: 'Oui, si personne ne vous a encore ajouté à l\'équipe d\'un recrutement. Un membre de l\'organisme ne voit que les recrutements sur lesquels il a un rôle. La page affiche alors « Vous n\'avez pas de recrutement en cours ». Pour accéder à un recrutement, demandez à un Superviseur de votre organisme de vous ajouter à l\'équipe du recrutement.',
    ou: 'Menu « Recrutements » › onglet « Recrutements en cours ».',
    motsCles: ['connexion', 'liste vide', 'aucun recrutement', 'premier accès'],
  },
  {
    id: 'dem-lien-collegue',
    theme: 'Démarrer',
    question: 'Un collègue m\'a envoyé le lien d\'un recrutement et je n\'arrive pas à l\'ouvrir : pourquoi ?',
    reponse: 'Un lien ne donne pas accès à lui seul. Il faut avoir un rôle sur ce recrutement (Responsable, Recruteur ou Contributeur) ou être Superviseur de l\'organisme. Sans ce rôle, la page « Accès refusé » s\'affiche. Demandez à un Superviseur de l\'organisme de vous ajouter à l\'équipe du recrutement.',
    ou: 'Le lien ouvre la page du recrutement ; en cas de refus, l\'écran « Accès refusé » s\'affiche.',
    motsCles: ['lien', 'partage', 'accès refusé', 'URL'],
  },
  {
    id: 'cand-voir',
    theme: 'Candidatures',
    question: 'Comment voir les candidatures d\'une offre, en colonnes ou en liste ?',
    reponse: 'Ouvrez l\'offre depuis la liste des recrutements. Les candidatures s\'affichent en colonnes, une par étape. Le bouton « Liste » les présente sous forme de tableau, et le bouton « Kanban » ramène aux colonnes. La recherche et les filtres fonctionnent dans les deux affichages.',
    ou: '« Recrutements » › intitulé de l\'offre › onglet « Candidatures » › « Kanban » / « Liste ».',
    motsCles: ['kanban', 'liste', 'colonnes', 'candidatures d\'une offre'],
  },
  {
    id: 'cand-etape-suivante',
    theme: 'Candidatures',
    question: 'Comment faire passer une candidature à l\'étape suivante ?',
    reponse: 'Deux possibilités :\n- dans les colonnes, glissez la carte du candidat vers la colonne de l\'étape voulue ;\n- depuis la fiche du candidat, cliquez sur « Changer d\'étape », choisissez l\'étape, puis « Valider ».\n\nUn message confirme le passage du candidat à la nouvelle étape.',
    ou: 'Onglet « Candidatures » (colonnes), ou fiche du candidat › « Changer d\'étape » › « Valider ».',
    motsCles: ['changer d\'étape', 'déplacer', 'glisser', 'avancer'],
  },
  {
    id: 'cand-lot',
    theme: 'Candidatures',
    question: 'Comment déplacer plusieurs candidatures en une seule fois ?',
    reponse: 'Sélectionnez les candidatures voulues dans les colonnes ; une case permet aussi de sélectionner toute une colonne. Une barre d\'actions apparaît : cliquez sur « Changer d\'étape », choisissez l\'étape cible, puis « Valider le changement d\'étape ».',
    ou: 'Onglet « Candidatures » › sélection › « Changer d\'étape » › « Valider le changement d\'étape ».',
    motsCles: ['plusieurs', 'lot', 'sélection multiple', 'en masse'],
  },
  {
    id: 'cand-bouton-grise',
    theme: 'Candidatures',
    question: 'Pourquoi le bouton de validation du changement d\'étape reste-t-il grisé ?',
    reponse: 'Le bouton s\'active une fois une étape choisie, différente de l\'étape actuelle des candidatures : l\'étape où elles se trouvent déjà ne peut pas être sélectionnée. Pour un refus, un motif doit aussi être choisi.',
    ou: 'Fenêtre « Changer d\'étape » ou fenêtre de refus.',
    motsCles: ['bouton grisé', 'valider impossible', 'inactif'],
  },
  {
    id: 'cand-refuser',
    theme: 'Candidatures',
    question: 'Comment refuser une candidature, et pourquoi un motif est-il obligatoire ?',
    reponse: 'Glissez la carte dans la colonne « Refus », ou sélectionnez les candidatures puis cliquez sur « Refuser ». Une fenêtre demande de choisir un motif ; « Valider le refus » ne s\'active qu\'une fois le motif choisi. La plateforme exige un motif pour toute candidature placée à l\'étape de refus.',
    ou: 'Onglet « Candidatures » › colonne « Refus » ou bouton « Refuser » › « Valider le refus ».',
    motsCles: ['refus', 'refuser', 'motif obligatoire'],
  },
  {
    id: 'cand-motifs',
    theme: 'Candidatures',
    question: 'Quels motifs de refus puis-je choisir, et le candidat les voit-il ?',
    reponse: 'Huit motifs sont proposés : corps ou grade non éligible ; condition de mobilité non remplie ; candidat non fonctionnaire ; expérience insuffisante ; compétences techniques insuffisantes ; niveau de qualification insuffisant ; disponibilité ; autre. Le motif de refus reste interne : il n\'est affiché nulle part côté candidat.',
    ou: 'Fenêtre de refus, au moment de placer une candidature à l\'étape « Refus ».',
    motsCles: ['motifs de refus', 'liste', 'candidat', 'confidentialité'],
  },
  {
    id: 'cand-echec-partiel',
    theme: 'Candidatures',
    question: 'Que signifie « Certaines candidatures n\'ont pas changé d\'étape » ?',
    reponse: 'Lors d\'un déplacement groupé, une partie des candidatures n\'a pas pu être déplacée parce qu\'elles n\'appartiennent plus à ce recrutement. Les autres ont bien changé d\'étape. Rechargez la page pour voir la situation à jour.',
    ou: 'Message affiché après « Valider le changement d\'étape ».',
    motsCles: ['certaines candidatures', 'échec partiel', 'pas déplacées'],
  },
  {
    id: 'cand-contributeur-etape',
    theme: 'Candidatures',
    question: 'Un Contributeur peut-il changer l\'étape d\'une candidature ?',
    reponse: 'Non. Le changement d\'étape est réservé au Responsable et au Recruteur du recrutement, ainsi qu\'aux Superviseurs de l\'organisme. Le Contributeur consulte les candidatures, leurs documents et leurs notes, et peut ajouter des notes.',
    ou: 'Sans objet (règle de droits).',
    motsCles: ['contributeur', 'droits', 'changer d\'étape'],
  },
  {
    id: 'cand-etape-precedente',
    theme: 'Candidatures',
    question: 'Peut-on ramener une candidature à une étape précédente ?',
    reponse: 'Oui. Aucun ordre n\'est imposé : une candidature peut être placée sur n\'importe quelle étape du recrutement, y compris une étape antérieure.',
    ou: 'Fiche du candidat › « Changer d\'étape », ou glisser la carte vers la colonne voulue.',
    motsCles: ['revenir', 'étape précédente', 'retour arrière', 'annuler'],
  },
  {
    id: 'cand-non-accessible',
    theme: 'Candidatures',
    question: 'Pourquoi est-ce que j\'obtiens « Cette candidature n\'est pas accessible » ?',
    reponse: 'Ce message apparaît quand la candidature n\'existe pas, a été supprimée, ou quand vous n\'avez pas de rôle sur le recrutement concerné. Par confidentialité, ces trois cas ne sont pas distingués. Contactez un Superviseur de votre organisme si besoin.',
    ou: 'Fiche du candidat.',
    motsCles: ['candidature non accessible', 'introuvable', 'accès'],
  },
  {
    id: 'cand-activites',
    theme: 'Candidatures',
    question: 'Que contient l\'onglet « Activités et tâches » ?',
    reponse: 'Cet onglet n\'est pas encore disponible ; il affiche « Activités et tâches (à venir) ».',
    ou: '« Recrutements » › intitulé de l\'offre › onglet « Activités et tâches ».',
    motsCles: ['activités', 'tâches', 'historique'],
  },
  {
    id: 'etp-defaut',
    theme: 'Étapes',
    question: 'Quelles étapes sont proposées par défaut ?',
    reponse: 'Six étapes, dans cet ordre : Réception des candidatures, Présélection, Entretien, Proposition, Refus, Recrutement.',
    ou: '« Paramètres de l\'organisme » › onglet « Étapes de recrutement ».',
    motsCles: ['étapes par défaut', 'processus', 'colonnes'],
  },
  {
    id: 'etp-organisme-offre',
    theme: 'Étapes',
    question: 'Quelle différence entre les étapes de l\'organisme et celles d\'une offre ?',
    reponse: 'Les étapes de l\'organisme servent de modèle. Chaque offre a ses propres étapes, modifiables sans toucher au modèle ni aux autres offres. Réinitialiser les étapes d\'une offre les remplace par les étapes actuelles de l\'organisme.',
    ou: 'Modèle : « Paramètres de l\'organisme » › « Étapes de recrutement ». Offre : page de l\'offre › « Actions sur l\'offre » › « Personnaliser les étapes de recrutement ».',
    motsCles: ['étapes organisme', 'étapes offre', 'modèle', 'personnaliser'],
  },
  {
    id: 'etp-qui-offre',
    theme: 'Étapes',
    question: 'Qui peut personnaliser les étapes d\'une offre ?',
    reponse: 'Le Responsable du recrutement et les Superviseurs de l\'organisme. Les Recruteurs et les Contributeurs ne peuvent pas modifier les étapes.',
    ou: 'Page de l\'offre › « Actions sur l\'offre » › « Personnaliser les étapes de recrutement ».',
    motsCles: ['personnaliser', 'droits', 'étapes de l\'offre'],
  },
  {
    id: 'etp-regles',
    theme: 'Étapes',
    question: 'Quelles règles dois-je respecter pour organiser les étapes ?',
    reponse: 'La première étape est toujours celle de réception des candidatures, l\'avant-dernière celle du refus, et la dernière celle du recrutement. Entre les deux, il faut au moins une étape intermédiaire, et seules des étapes intermédiaires peuvent y être placées. Deux étapes ne peuvent pas porter le même nom.',
    ou: 'Écran des étapes (organisme ou offre) › « Ajouter une étape ».',
    motsCles: ['règles', 'ordre', 'ajouter une étape', 'erreur'],
  },
  {
    id: 'etp-verrouillees',
    theme: 'Étapes',
    question: 'Pourquoi ne puis-je ni déplacer ni supprimer certaines étapes ?',
    reponse: 'La première étape, l\'étape de refus et l\'étape de recrutement sont fixes : elles ne peuvent être ni déplacées, ni supprimées, ni encadrées par une nouvelle étape. Elles peuvent en revanche être renommées. Seules les étapes intermédiaires se déplacent et se suppriment.',
    ou: 'Écran des étapes › menu d\'une étape (« Monter », « Descendre », « Supprimer », « Renommer »).',
    motsCles: ['déplacer', 'supprimer', 'étape bloquée', 'grisé'],
  },
  {
    id: 'etp-supprimer-pleine',
    theme: 'Étapes',
    question: 'Puis-je supprimer une étape qui contient encore des candidatures ?',
    reponse: 'Non. La suppression est refusée tant que des candidatures sont à cette étape. Déplacez d\'abord ces candidatures vers une autre étape, puis supprimez l\'étape.',
    ou: 'Écran des étapes › menu de l\'étape › « Supprimer ».',
    motsCles: ['supprimer', 'étape avec candidatures'],
  },
  {
    id: 'etp-propagation',
    theme: 'Étapes',
    question: 'Si je modifie les étapes de l\'organisme, les offres déjà ouvertes changent-elles aussi ?',
    reponse: 'Non. Modifier les étapes de l\'organisme ne change que le modèle ; les offres existantes conservent leurs étapes. Une offre ne reprend les étapes de l\'organisme que si ses étapes sont réinitialisées.',
    ou: '« Paramètres de l\'organisme » › onglet « Étapes de recrutement ».',
    motsCles: ['modifier étapes organisme', 'offres existantes', 'propagation'],
  },
  {
    id: 'etp-qui-organisme',
    theme: 'Étapes',
    question: 'Qui peut modifier les étapes par défaut de l\'organisme ?',
    reponse: 'Les Superviseurs de l\'organisme. Les Membres n\'ont pas accès aux paramètres de l\'organisme.',
    ou: '« Paramètres de l\'organisme » › onglet « Étapes de recrutement ».',
    motsCles: ['étapes par défaut', 'modèle', 'droits'],
  },
  {
    id: 'rec-liste',
    theme: 'Recrutements',
    question: 'Quels recrutements apparaissent dans ma liste ?',
    reponse: 'Un Superviseur de l\'organisme voit tous les recrutements de l\'organisme. Un Membre ne voit que ceux sur lesquels il a un rôle (Responsable, Recruteur ou Contributeur du recrutement).',
    ou: 'Menu « Recrutements ».',
    motsCles: ['mes recrutements', 'liste', 'visibilité'],
  },
  {
    id: 'rec-en-cours-termines',
    theme: 'Recrutements',
    question: 'Quelle différence entre « Recrutements en cours » et « Recrutements terminés » ?',
    reponse: '« Recrutements en cours » regroupe les recrutements actifs. « Recrutements terminés » regroupe les recrutements archivés.',
    ou: 'Menu « Recrutements » › onglets « Recrutements en cours » / « Recrutements terminés ».',
    motsCles: ['en cours', 'terminés', 'archivés', 'onglets'],
  },
  {
    id: 'rec-rechercher',
    theme: 'Recrutements',
    question: 'Comment retrouver une offre précise ?',
    reponse: 'Tapez le nom de l\'offre ou sa référence dans le champ de recherche, ou utilisez « Filtres » puis « Appliquer les filtres ». « Réinitialiser » efface les filtres.',
    ou: 'Menu « Recrutements » › « Rechercher un recrutement » / « Filtres ».',
    motsCles: ['recherche', 'filtres', 'retrouver une offre'],
  },
  {
    id: 'rec-designer-responsable',
    theme: 'Recrutements',
    question: 'Comment désigner le responsable d\'un ou de plusieurs recrutements ?',
    reponse: 'Cochez les recrutements concernés, puis cliquez sur « Assigner un responsable ». Saisissez l\'adresse électronique de la personne et validez. Si elle n\'a pas encore de compte, il est créé à cette occasion. Cette action est réservée aux Superviseurs de l\'organisme.',
    ou: 'Menu « Recrutements » › onglet « Recrutements en cours » › cases à cocher › « Assigner un responsable ».',
    motsCles: ['responsable', 'assigner', 'désigner', 'plusieurs offres'],
  },
  {
    id: 'rec-cases-absentes',
    theme: 'Recrutements',
    question: 'Pourquoi ne puis-je pas cocher de recrutements dans la liste ?',
    reponse: 'Les cases de sélection ne servent qu\'à désigner un responsable, une action réservée aux Superviseurs de l\'organisme. Elles ne s\'affichent pas pour les Membres.',
    ou: 'Menu « Recrutements » › onglet « Recrutements en cours ».',
    motsCles: ['cases à cocher', 'sélection', 'absente'],
  },
  {
    id: 'rec-assignation-partielle',
    theme: 'Recrutements',
    question: 'Que veut dire « Assignation partielle » après la désignation d\'un responsable ?',
    reponse: 'Le responsable a été désigné sur une partie des offres sélectionnées seulement. Les offres ignorées n\'ont pas été trouvées dans votre organisme. Le message indique combien d\'offres ont été ignorées.',
    ou: 'Message affiché après « Assigner un responsable ».',
    motsCles: ['assignation partielle', 'offres ignorées'],
  },
  {
    id: 'rec-membre-plus-rattache',
    theme: 'Recrutements',
    question: 'Que veut dire « Ce membre n\'est plus rattaché à l\'organisme » quand je désigne un responsable ?',
    reponse: 'La personne choisie ne fait plus partie de votre organisme. Vérifiez la liste des membres et, si besoin, rattachez-la de nouveau avant de la désigner.',
    ou: '« Paramètres de l\'organisme » › onglet « Membres ».',
    motsCles: ['membre plus rattaché', 'assignation impossible'],
  },
  {
    id: 'org-superviseur-agent',
    theme: 'Organisme et équipe',
    question: 'Quelle différence entre un Superviseur et un Membre de l\'organisme ?',
    reponse: 'Le Superviseur de l\'organisme gère l\'organisme : membres, étapes par défaut, désignation des responsables de recrutement, accès à tous les recrutements. Le Membre travaille sur les recrutements où il a un rôle (Responsable, Recruteur ou Contributeur du recrutement).',
    ou: '« Paramètres de l\'organisme » › onglet « Membres » (colonne du rôle), réservé au Superviseur de l\'organisme. Un Membre voit son rôle de recrutement dans l\'onglet « Équipe de recrutement ».',
    motsCles: ['superviseur', 'membre', 'rôle organisme', 'différence'],
  },
  {
    id: 'org-parametres-qui',
    theme: 'Organisme et équipe',
    question: 'Qui peut voir et modifier les paramètres de mon organisme ?',
    reponse: 'Les Superviseurs de l\'organisme. Pour eux seuls, le menu affiche « Paramètres de l\'organisme », qui regroupe les membres et les étapes de recrutement par défaut.',
    ou: 'Menu « Paramètres de l\'organisme ».',
    motsCles: ['paramètres de l\'organisme', 'accès', 'menu absent'],
  },
  {
    id: 'org-ajouter-membre',
    theme: 'Organisme et équipe',
    question: 'Comment ajouter un collègue à mon organisme ?',
    reponse: 'Cliquez sur « Ajouter un membre » et saisissez son adresse électronique. Choisissez ensuite son rôle dans l\'organisme, puis cliquez sur « Ajouter le membre ».',
    ou: '« Paramètres de l\'organisme » › onglet « Membres » › « Ajouter un membre ».',
    motsCles: ['ajouter un membre', 'inviter', 'collègue'],
  },
  {
    id: 'org-sans-compte',
    theme: 'Organisme et équipe',
    question: 'Mon collègue n\'a pas encore de compte sur la plateforme : puis-je quand même l\'ajouter ?',
    reponse: 'Oui. Si aucun compte ne correspond à l\'adresse, la plateforme l\'indique et propose « Créer et ajouter ». Le compte est créé ; la personne complétera son profil à sa première connexion.',
    ou: '« Paramètres de l\'organisme » › « Membres » › « Ajouter un membre » › « Créer et ajouter ».',
    motsCles: ['pas de compte', 'création de compte', 'invitation'],
  },
  {
    id: 'org-deja-rattache',
    theme: 'Organisme et équipe',
    question: 'Que signifie le message « Cet agent est déjà rattaché à l\'organisme » ?',
    reponse: 'La personne fait déjà partie de votre organisme : il n\'y a rien à faire. Pour changer son rôle, utilisez le menu de sa ligne dans la liste des membres.',
    ou: '« Paramètres de l\'organisme » › onglet « Membres ».',
    motsCles: ['déjà rattaché', 'doublon', 'ajout impossible'],
  },
  {
    id: 'org-changer-role',
    theme: 'Organisme et équipe',
    question: 'Comment changer le rôle d\'un membre de l\'organisme ?',
    reponse: 'Dans la liste des membres, ouvrez le menu de la ligne de la personne et choisissez le changement de rôle proposé.',
    ou: '« Paramètres de l\'organisme » › onglet « Membres » › menu de la ligne › « Passer membre » / « Passer superviseur ».',
    motsCles: ['changer de rôle', 'promouvoir', 'superviseur'],
  },
  {
    id: 'org-revoquer',
    theme: 'Organisme et équipe',
    question: 'Comment retirer l\'accès d\'un collègue qui quitte le service ?',
    reponse: 'Dans la liste des membres, ouvrez le menu de la ligne de la personne, choisissez « Révoquer », puis confirmez avec « Révoquer les accès ».',
    ou: '« Paramètres de l\'organisme » › onglet « Membres » › menu de la ligne › « Révoquer ».',
    motsCles: ['révoquer', 'départ', 'retirer l\'accès', 'retirer', 'quitte', 'supprimer un membre'],
  },
  {
    id: 'org-apres-revocation',
    theme: 'Organisme et équipe',
    question: 'Une personne dont j\'ai révoqué l\'accès peut-elle encore se connecter ou voir nos recrutements ?',
    reponse: 'Non. Une fois révoquée, la personne n\'accède plus à votre organisme ni à ses recrutements. Si elle n\'est rattachée à aucun autre organisme, elle ne peut plus se connecter.',
    ou: 'Sans objet.',
    motsCles: ['révocation', 'accès après départ', 'connexion'],
  },
  {
    id: 'org-equipe-definition',
    theme: 'Organisme et équipe',
    question: 'Qu\'est-ce que l\'équipe de recrutement d\'une offre ?',
    reponse: 'Ce sont les personnes qui travaillent sur ce recrutement, chacune avec un rôle dans le recrutement : Responsable, Recruteur ou Contributeur. Ce rôle détermine ce que chacun peut faire sur les candidatures de l\'offre.',
    ou: '« Recrutements » › intitulé de l\'offre › onglet « Équipe de recrutement ».',
    motsCles: ['équipe de recrutement', 'membres de l\'offre'],
  },
  {
    id: 'org-roles-offre',
    theme: 'Organisme et équipe',
    question: 'Quelle différence entre Responsable, Recruteur et Contributeur dans un recrutement ?',
    reponse: 'Tous trois consultent les candidatures, leurs documents et leurs notes, et peuvent ajouter des notes. Le Recruteur et le Responsable du recrutement changent en plus l\'étape des candidatures. Seul le Responsable du recrutement personnalise ses étapes.',
    ou: 'Sans objet (règle de droits).',
    motsCles: ['responsable', 'recruteur', 'contributeur', 'différence'],
  },
  {
    id: 'org-deja-equipe',
    theme: 'Organisme et équipe',
    question: 'Que signifie le message « Cette personne fait déjà partie de l\'équipe » ?',
    reponse: 'La personne est déjà membre de l\'équipe de ce recrutement. Pour modifier son rôle, utilisez le menu de sa ligne dans l\'équipe.',
    ou: '« Recrutements » › intitulé de l\'offre › onglet « Équipe de recrutement ».',
    motsCles: ['déjà dans l\'équipe', 'doublon'],
  },
  {
    id: 'org-role-equipe',
    theme: 'Organisme et équipe',
    question: 'Comment changer le rôle d\'une personne dans l\'équipe d\'un recrutement ?',
    reponse: 'Dans l\'équipe de recrutement, ouvrez le menu de la ligne de la personne et choisissez le nouveau rôle.',
    ou: 'Onglet « Équipe de recrutement » › menu de la ligne › « Passer responsable » / « Passer recruteur » / « Passer contributeur ».',
    motsCles: ['changer de rôle', 'équipe', 'recruteur', 'contributeur'],
  },
  {
    id: 'org-creer-organisme',
    theme: 'Organisme et équipe',
    question: 'Qui peut créer un nouvel organisme sur la plateforme ?',
    reponse: 'Uniquement les administrateurs de la plateforme. Si votre organisme n\'existe pas encore, adressez-vous à l\'équipe de la plateforme.',
    ou: 'Réservé aux administrateurs : « Gestion des organismes » › « Ajouter un organisme ».',
    motsCles: ['créer un organisme', 'nouvel organisme'],
  },
  {
    id: 'org-siret',
    theme: 'Organisme et équipe',
    question: 'Pourquoi ne puis-je pas modifier le SIRET d\'un organisme, et que veut dire « Ce SIRET est déjà utilisé ou n\'est pas valide » ?',
    reponse: 'Le SIRET est fixé à la création de l\'organisme et ne se modifie plus ensuite. À la création, ce message signifie qu\'un organisme utilise déjà ce SIRET ou que le numéro saisi n\'est pas valide.',
    ou: 'Réservé aux administrateurs : « Gestion des organismes » › « Ajouter un organisme » / « Modifier l\'organisme ».',
    motsCles: ['SIRET', 'modifier', 'déjà utilisé', 'invalide'],
  },
  {
    id: 'org-modifier-infos',
    theme: 'Organisme et équipe',
    question: 'Qui peut modifier le nom ou les informations d\'un organisme ?',
    reponse: 'Uniquement les administrateurs de la plateforme. Pour une correction, adressez-vous à l\'équipe de la plateforme.',
    ou: 'Réservé aux administrateurs : « Gestion des organismes » › « Modifier l\'organisme » › « Enregistrer les modifications ».',
    motsCles: ['modifier l\'organisme', 'nom', 'informations'],
  },
  {
    id: 'doc-note-ajouter',
    theme: 'Notes, documents, messages',
    question: 'Comment ajouter une note sur une candidature, et qui peut la lire ?',
    reponse: 'Dans la fiche du candidat, rédigez la note dans la colonne de droite, puis cliquez sur « Enregistrer la note ». Elle est lisible par toutes les personnes qui ont accès à la candidature : l\'équipe du recrutement et les Superviseurs de l\'organisme.',
    ou: 'Fiche du candidat › colonne de droite › « Enregistrer la note » ; lecture dans l\'onglet « Notes ».',
    motsCles: ['note', 'commentaire', 'ajouter', 'qui voit'],
  },
  {
    id: 'doc-note-modifier',
    theme: 'Notes, documents, messages',
    question: 'Puis-je modifier ou supprimer une note ?',
    reponse: 'Pas encore depuis l\'interface : une note enregistrée ne peut être ni modifiée ni supprimée.',
    ou: 'Sans objet.',
    motsCles: ['modifier une note', 'supprimer une note'],
  },
  {
    id: 'doc-cv',
    theme: 'Notes, documents, messages',
    question: 'Où trouver le CV et les pièces jointes d\'un candidat ?',
    reponse: 'Le CV s\'affiche dans l\'onglet « Candidature » de la fiche, avec « Afficher pleine page » et « Télécharger ». Les autres pièces sont dans l\'onglet « Documents », avec « Voir » et « Télécharger ».',
    ou: 'Fiche du candidat › onglets « Candidature » et « Documents ».',
    motsCles: ['CV', 'pièces jointes', 'documents', 'télécharger'],
  },
  {
    id: 'doc-non-consultable',
    theme: 'Notes, documents, messages',
    question: 'Pourquoi certains documents ne s\'ouvrent-ils pas dans la plateforme ?',
    reponse: 'Seuls les documents au format PDF peuvent être consultés et téléchargés dans la plateforme. Pour les autres formats, aucun lien n\'est proposé.',
    ou: 'Fiche du candidat › onglet « Documents ».',
    motsCles: ['document ne s\'ouvre pas', 'format', 'PDF'],
  },
  {
    id: 'doc-messagerie',
    theme: 'Notes, documents, messages',
    question: 'Puis-je écrire à un candidat depuis la plateforme ?',
    reponse: 'La messagerie n\'est pas encore disponible. L\'onglet « Messages » est visible, mais les boutons « Démarrer une conversation » et « Envoyer » sont désactivés.',
    ou: 'Fiche du candidat › onglet « Messages ».',
    motsCles: ['message', 'écrire au candidat', 'messagerie'],
  },
  {
    id: 'droits-qui-fait-quoi',
    theme: 'Droits et rôles',
    question: 'Qui peut faire quoi dans la plateforme ?',
    reponse: 'Cela dépend de votre rôle.\n- Le Superviseur de l\'organisme peut tout faire dans l\'organisme : gérer les membres, les étapes par défaut et les équipes, désigner les responsables de recrutement et accéder à tous les recrutements.\n- Le Responsable d\'un recrutement gère les candidatures, les étapes et les notes de ce recrutement.\n- Le Recruteur traite les candidatures, y compris le changement d\'étape, et rédige des notes.\n- Le Contributeur consulte les candidatures et les documents, et peut ajouter des notes.\n- Un Membre sans rôle sur un recrutement n\'y a pas accès.',
    ou: 'Votre rôle dans un recrutement : onglet « Équipe de recrutement » du recrutement. Les rôles dans l\'organisme : « Paramètres de l\'organisme » › onglet « Membres », réservé au Superviseur de l\'organisme.',
    motsCles: ['droits', 'matrice', 'qui peut', 'permissions', 'rôles', 'autorisations'],
  },
  {
    id: 'droits-role-organisme',
    theme: 'Droits et rôles',
    question: 'Mon rôle dans l\'organisme me donne-t-il accès à toutes les offres ?',
    reponse: 'Seulement si vous êtes Superviseur de l\'organisme. Un Membre n\'accède qu\'aux recrutements sur lesquels il a un rôle (Responsable, Recruteur ou Contributeur du recrutement).',
    ou: 'Menu « Recrutements ».',
    motsCles: ['accès aux offres', 'rôle organisme', 'toutes les offres'],
  },
  {
    id: 'droits-superviseur-responsable',
    theme: 'Droits et rôles',
    question: 'Quelle différence entre un Superviseur et le Responsable d\'un recrutement ?',
    reponse: 'Ce sont deux niveaux de rôle. Le Superviseur est un rôle dans l\'organisme : il gère l\'organisme et accède à tous ses recrutements. Le Responsable est un rôle dans un recrutement : il pilote ce seul recrutement. Une même personne peut être Membre de l\'organisme et Responsable d\'un recrutement.',
    ou: 'Rôle dans le recrutement : onglet « Équipe de recrutement ». Rôle dans l\'organisme : « Paramètres de l\'organisme » › onglet « Membres », réservé au Superviseur de l\'organisme.',
    motsCles: ['superviseur', 'responsable', 'vocabulaire', 'libellé', 'rôles'],
  },
  {
    id: 'pb-acces-refuse',
    theme: 'Problèmes courants',
    question: 'Que veut dire l\'écran « Accès refusé », et que faire ?',
    reponse: 'Votre compte n\'a pas de droit sur la page demandée, par exemple un recrutement dont vous ne faites pas partie ou les paramètres de l\'organisme. Rapprochez-vous d\'un Superviseur de votre organisme si vous pensez que c\'est une erreur.',
    ou: 'Écran « Accès refusé ».',
    motsCles: ['accès refusé', 'pas autorisé'],
  },
  {
    id: 'pb-page-introuvable',
    theme: 'Problèmes courants',
    question: 'Que veut dire « Page introuvable » ?',
    reponse: 'Le lien est incorrect, ou la page demandée n\'existe pas (par exemple un organisme inconnu). Utilisez « Retour à l\'accueil » puis le menu.',
    ou: 'Écran « Page introuvable » › « Retour à l\'accueil ».',
    motsCles: ['page introuvable', 'lien cassé'],
  },
  {
    id: 'pb-chargement',
    theme: 'Problèmes courants',
    question: 'Que faire quand s\'affiche « Impossible de charger l\'équipe de recrutement », « Impossible de charger les membres » ou « Une erreur est survenue. Veuillez réessayer. » ?',
    reponse: 'Ces messages apparaissent quand la page n\'a pas pu être chargée, en particulier quand votre rôle ne donne pas accès à son contenu. Vérifiez votre rôle sur l\'organisme ou sur l\'offre auprès d\'un Superviseur de l\'organisme ; si vous avez les droits, réessayez plus tard.',
    ou: 'Onglet « Équipe de recrutement », onglet « Membres », écran des étapes.',
    motsCles: ['impossible de charger', 'erreur', 'réessayer'],
  },
  {
    id: 'pb-note-non-enregistree',
    theme: 'Problèmes courants',
    question: 'Une fenêtre « Modifications non enregistrées » s\'ouvre quand je quitte une candidature : que faire ?',
    reponse: 'Vous avez commencé à écrire une note sans l\'enregistrer. « Continuer l\'édition » vous ramène à la note pour l\'enregistrer. « Quitter sans enregistrer » abandonne le texte saisi.',
    ou: 'Fiche du candidat › fenêtre « Modifications non enregistrées ».',
    motsCles: ['modifications non enregistrées', 'quitter', 'note perdue'],
  },
  {
    id: 'pb-session-expiree',
    theme: 'Problèmes courants',
    question: 'Je suis renvoyé vers la page de connexion en pleine navigation : pourquoi ?',
    reponse: 'Votre session a expiré. Reconnectez-vous pour reprendre votre travail.',
    ou: 'Page de connexion.',
    motsCles: ['déconnecté', 'session expirée', 'page de connexion'],
  },
] satisfies FaqEntree[]
