# Generated by Django 6.0.5 on 2026-05-29 08:09

from django.db import migrations, models

from uuid import uuid4


def forward(apps, schema_editor):
    UserModel = apps.get_model("users", "UserModel")
    users = UserModel.objects.all()
    for user in users:
        user.username=uuid4()
    UserModel.objects.bulk_update(users, ["username"])

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_usermodel_options_alter_usermodel_email"),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="usermodel",
            name="username",
            field=models.CharField(editable=False, max_length=36, unique=True),
        ),
    ]
