# Generated by Django 6.0.6 on 2026-06-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0026_apilogmodel'),
        ('users', '0004_alter_usermodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='users', to='ingestion.sourcemodel', verbose_name='Sources'),
        ),
    ]
