# Generated by Django 6.0.6 on 2026-06-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_sources_to_user'),
        ('users', '0006_profilcandidatmodel'),
    ]

    operations = [
    ]
