# Generated by Django 6.1 on 2026-08-19 14:05

import uuid

from django.db import migrations, models


def check_usernames_are_valid_uuids(apps, schema_editor):
    UserModel = apps.get_model("users", "UserModel")
    invalid = [
        (user.pk, user.username)
        for user in UserModel.objects.all().only("pk", "username")
        if not _is_valid_uuid(user.username)
    ]
    if invalid:
        raise RuntimeError(
            "Cannot convert UserModel.username to UUIDField: found non-UUID "
            f"username values for user pks {invalid}. Fix or remove these rows "
            "before migrating."
        )


def _is_valid_uuid(value) -> bool:
    try:
        uuid.UUID(str(value))
    except (ValueError, AttributeError, TypeError):
        return False
    return True


def _drop_pattern_ops_index_sql(table: str, column: str) -> str:
    return f"""
        DO $$
        DECLARE
            idx_name text;
        BEGIN
            SELECT ic.relname INTO idx_name
            FROM pg_index ix
            JOIN pg_class ic ON ic.oid = ix.indexrelid
            JOIN pg_class tc ON tc.oid = ix.indrelid
            JOIN pg_attribute a ON a.attrelid = tc.oid AND a.attnum = ANY(ix.indkey)
            JOIN pg_opclass oc ON oc.oid = ANY(ix.indclass)
            WHERE tc.relname = '{table}'
              AND a.attname = '{column}'
              AND oc.opcname IN ('varchar_pattern_ops', 'text_pattern_ops')
            LIMIT 1;

            IF idx_name IS NOT NULL THEN
                EXECUTE format('DROP INDEX IF EXISTS %I', idx_name);
            END IF;
        END $$;
    """  # noqa: S608


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_merge_20260612_1624"),
    ]

    operations = [
        migrations.RunPython(
            check_usernames_are_valid_uuids, migrations.RunPython.noop
        ),
        migrations.RunSQL(
            _drop_pattern_ops_index_sql("users_usermodel", "username"),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            _drop_pattern_ops_index_sql("users_profilagentmodel", "utilisateur_id"),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            _drop_pattern_ops_index_sql("users_profilcandidatmodel", "utilisateur_id"),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="username",
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
