openapi: 3.0.3
info:
  title: CSPLab Internal API
  version: 0.0.1
paths:
  /recruteur/organisme/{organisme_uuid}/:
    get:
      operationId: recruteur_organisme_retrieve
      summary: Detail d'un organisme
      parameters:
      - in: path
        name: organisme_uuid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - recruteur
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organisme'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenError'
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: ''
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: ''
  /recruteur/organisme/{organisme_uuid}/parametres/etapes/:
    get:
      operationId: recruteur_organisme_parametres_etapes_list
      summary: Liste des étapes de recrutement d'un organisme
      parameters:
      - in: path
        name: organisme_uuid
        schema:
          type: string
          format: uuid
        required: true
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - recruteur
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedEtapeRecrutementList'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenError'
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: ''
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: ''
  /utilisateur/me/:
    get:
      operationId: utilisateur_me_retrieve
      summary: Detail de l'utilisateur connecté
      tags:
      - utilisateurs
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Utilisateur'
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenError'
          description: ''
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: ''
components:
  schemas:
    CategorieEnum:
      enum:
      - INITIALE
      - EN_COURS
      - TERMINALE
      type: string
      description: |-
        * `INITIALE` - initiale
        * `EN_COURS` - en_cours
        * `TERMINALE` - terminale
    EtapeRecrutement:
      type: object
      properties:
        etape_uuid:
          type: string
          format: uuid
        nom:
          type: string
        categorie:
          $ref: '#/components/schemas/CategorieEnum'
      required:
      - categorie
      - etape_uuid
      - nom
    GenericError:
      type: object
      properties:
        error:
          type: string
      required:
      - error
    Organisme:
      type: object
      properties:
        nom:
          type: string
          format: email
        siret:
          type: string
      required:
      - nom
      - siret
    PaginatedEtapeRecrutementList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/EtapeRecrutement'
    TokenError:
      type: object
      properties:
        detail:
          type: string
        code:
          type: string
        messages:
          type: array
          items:
            $ref: '#/components/schemas/TokenErrorMessage'
      required:
      - code
      - detail
      - messages
    TokenErrorMessage:
      type: object
      properties:
        token_class:
          type: string
        token_type:
          type: string
        message:
          type: string
      required:
      - message
      - token_class
      - token_type
    Utilisateur:
      type: object
      properties:
        email:
          type: string
          format: email
        prenom:
          type: string
        nom:
          type: string
      required:
      - email
      - nom
      - prenom
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
- name: utilisateurs
  description: Gestion des utilisateurs
