# Generated by Django 6.0.6 on 2026-06-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLogModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_id", models.UUIDField(db_index=True, null=True)),
                ("occurred_at", models.DateTimeField()),
                ("utilisateur_id", models.UUIDField()),
                ("event_name", models.CharField(max_length=255)),
                ("ressource_kind", models.CharField(max_length=255)),
                ("ressource_id", models.UUIDField()),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["ressource_kind", "ressource_id"],
                        name="audit_logs_ressource_idx",
                    ),
                    models.Index(
                        fields=["utilisateur_id"], name="audit_logs_utilisateur_idx"
                    ),
                ],
            },
        ),
    ]
