# Generated by Django 6.1.1 on 2026-10-01 10:20

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0002_statsnapshotmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLoginLogModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "utilisateur_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("admin", "Admin Django"),
                            ("jwt", "API (JWT)"),
                            ("apikey", "API (clé d'API)"),
                            ("proconnect", "ProConnect"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "resultat",
                    models.CharField(
                        choices=[("succes", "Succès"), ("echec", "Échec")],
                        max_length=10,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "db_table": "audit_login_logs",
                "ordering": ["-occurred_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("resultat", "succes"), _negated=True),
                            ("utilisateur_id__isnull", False),
                            ("canal", "apikey"),
                            _connector="OR",
                        ),
                        name="audit_login_logs_succes_has_user",
                    )
                ],
            },
        ),
    ]
