from datetime import datetime, timezone
from typing import List, Tuple, cast

from ddd.services.async_http_client_interface import IAsyncHttpClient
from ddd.services.logger_interface import ILogger
from ddd.types import JsonDataType

from domain.ingestion.entities.document import Document, DocumentType
from domain.ingestion.gateways.document_gateway_interface import IDocumentGateway
from infrastructure.external_gateways.dtos.ingres_corps_dtos import (
    IngresCorpsApiResponse,
)
from infrastructure.external_gateways.dtos.ingres_metiers_dtos import (
    IngresMetiersApiResponse,
)


class ExternalDocumentGateway(IDocumentGateway):
    def __init__(
        self,
        piste_client: IAsyncHttpClient,
        logger_service: ILogger,
    ):
        self.piste_client = piste_client
        self.logger = logger_service
        self._source = {
            DocumentType.CORPS: self._fetch_ingres_api,
            DocumentType.METIERS: self._fetch_ingres_api,
        }

    async def fetch_by_type(
        self, document_type: DocumentType, start: int = 1, batch_size: int = 1000
    ) -> Tuple[List[Document], bool]:
        self.logger.info("Fetching documents of type %s", document_type)

        source = self._source.get(document_type)
        if not source:
            raise ValueError(f"No fetch source for {document_type}")

        raw_documents, has_more = await source(document_type, start, batch_size)
        now = datetime.now(timezone.utc)

        documents = []

        if document_type == DocumentType.CORPS:
            typed_raw_documents = cast(List[dict], raw_documents)
            corps_response = IngresCorpsApiResponse.from_list(typed_raw_documents)

            for corps_doc in corps_response.documents:
                document = Document(
                    external_id=str(corps_doc.identifiant),
                    raw_data=corps_doc.model_dump(),
                    type=document_type,
                    created_at=now,
                    # id will be auto-generated by Document entity
                )
                documents.append(document)

        elif document_type == DocumentType.METIERS:
            typed_raw_documents = cast(List[dict], raw_documents)
            metiers_response = IngresMetiersApiResponse.from_list(typed_raw_documents)

            for metiers_doc in metiers_response.documents:
                document = Document(
                    external_id=str(metiers_doc.identifiant),
                    raw_data=metiers_doc.model_dump(),
                    type=document_type,
                    created_at=now,
                    # id will be auto-generated by Document entity
                )
                documents.append(document)

        return documents, has_more

    async def _fetch_ingres_api(
        self, document_type: DocumentType, start: int = 1, batch_size: int = 1000
    ) -> Tuple[List[JsonDataType], bool]:
        document_type_map = {
            DocumentType.CORPS: "CORPS",
            DocumentType.METIERS: "RMFP_EMPL_REF",
        }

        endpoint = document_type_map.get(document_type)
        if endpoint is None:
            raise ValueError(f"Ingres: unknown document type: {document_type}")

        async with self.piste_client:
            response = await self.piste_client.get(
                endpoint, params={"enVigueur": "true", "full": "true"}
            )

        response_data = response.json()
        if not isinstance(response_data, dict) or "items" not in response_data:
            raise ValueError(f"Invalid API response format: {response_data}")

        raw_documents = response_data["items"]
        if not isinstance(raw_documents, list):
            raise ValueError(f"Expected list of documents, got {type(raw_documents)}")

        self.logger.info("Found %d documents", len(raw_documents))

        has_more = False
        return cast(List[JsonDataType], raw_documents), has_more
