import logging
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class ILogger(Protocol):
    def get_logger(self, module_name: str) -> logging.Logger: ...

    def info(self, message: str, *args: Any) -> None: ...

    def debug(self, message: str, *args: Any) -> None: ...

    def warning(self, message: str, *args: Any) -> None: ...

    def error(self, message: str, *args: Any) -> None: ...
