// Generated by scripts/build-icons.mjs from the ri:* names used in src/.
// Do not edit: run `pnpm icons` to regenerate.
import riAddLine from '@iconify-icons/ri/add-line'
import riAlertFill from '@iconify-icons/ri/alert-fill'
import riAlertLine from '@iconify-icons/ri/alert-line'
import riArchiveLine from '@iconify-icons/ri/archive-line'
import riArrowDownLine from '@iconify-icons/ri/arrow-down-line'
import riArrowDownSLine from '@iconify-icons/ri/arrow-down-s-line'
import riArrowLeftDoubleLine from '@iconify-icons/ri/arrow-left-double-line'
import riArrowLeftLine from '@iconify-icons/ri/arrow-left-line'
import riArrowLeftRightLine from '@iconify-icons/ri/arrow-left-right-line'
import riArrowLeftSLine from '@iconify-icons/ri/arrow-left-s-line'
import riArrowRightDoubleLine from '@iconify-icons/ri/arrow-right-double-line'
import riArrowRightLine from '@iconify-icons/ri/arrow-right-line'
import riArrowRightSLine from '@iconify-icons/ri/arrow-right-s-line'
import riArrowUpLine from '@iconify-icons/ri/arrow-up-line'
import riArrowUpSLine from '@iconify-icons/ri/arrow-up-s-line'
import riBookmarkLine from '@iconify-icons/ri/bookmark-line'
import riBriefcaseLine from '@iconify-icons/ri/briefcase-line'
import riCalendarLine from '@iconify-icons/ri/calendar-line'
import riCheckLine from '@iconify-icons/ri/check-line'
import riCheckboxCircleFill from '@iconify-icons/ri/checkbox-circle-fill'
import riCheckboxCircleLine from '@iconify-icons/ri/checkbox-circle-line'
import riCloseCircleLine from '@iconify-icons/ri/close-circle-line'
import riCloseLine from '@iconify-icons/ri/close-line'
import riCompass3Line from '@iconify-icons/ri/compass-3-line'
import riDashboardLine from '@iconify-icons/ri/dashboard-line'
import riDeleteBinLine from '@iconify-icons/ri/delete-bin-line'
import riDraggable from '@iconify-icons/ri/draggable'
import riEditLine from '@iconify-icons/ri/edit-line'
import riErrorWarningFill from '@iconify-icons/ri/error-warning-fill'
import riErrorWarningLine from '@iconify-icons/ri/error-warning-line'
import riExpandUpDownLine from '@iconify-icons/ri/expand-up-down-line'
import riExternalLinkLine from '@iconify-icons/ri/external-link-line'
import riEyeLine from '@iconify-icons/ri/eye-line'
import riFileCopyLine from '@iconify-icons/ri/file-copy-line'
import riFilter3Line from '@iconify-icons/ri/filter-3-line'
import riFilterLine from '@iconify-icons/ri/filter-line'
import riFlashlightFill from '@iconify-icons/ri/flashlight-fill'
import riGovernmentLine from '@iconify-icons/ri/government-line'
import riGroupLine from '@iconify-icons/ri/group-line'
import riHomeLine from '@iconify-icons/ri/home-line'
import riInbox2Line from '@iconify-icons/ri/inbox-2-line'
import riInformationFill from '@iconify-icons/ri/information-fill'
import riInformationLine from '@iconify-icons/ri/information-line'
import riLayoutColumnLine from '@iconify-icons/ri/layout-column-line'
import riLayoutGridLine from '@iconify-icons/ri/layout-grid-line'
import riLightbulbLine from '@iconify-icons/ri/lightbulb-line'
import riListCheck from '@iconify-icons/ri/list-check'
import riListUnordered from '@iconify-icons/ri/list-unordered'
import riLogoutBoxRLine from '@iconify-icons/ri/logout-box-r-line'
import riMailLine from '@iconify-icons/ri/mail-line'
import riMapPin2Line from '@iconify-icons/ri/map-pin-2-line'
import riMenuLine from '@iconify-icons/ri/menu-line'
import riMoonLine from '@iconify-icons/ri/moon-line'
import riMore2Fill from '@iconify-icons/ri/more-2-fill'
import riMore2Line from '@iconify-icons/ri/more-2-line'
import riMoreFill from '@iconify-icons/ri/more-fill'
import riNotification3Line from '@iconify-icons/ri/notification-3-line'
import riPencilLine from '@iconify-icons/ri/pencil-line'
import riPriceTag3Line from '@iconify-icons/ri/price-tag-3-line'
import riRefreshLine from '@iconify-icons/ri/refresh-line'
import riRestartLine from '@iconify-icons/ri/restart-line'
import riSearchLine from '@iconify-icons/ri/search-line'
import riSettings3Line from '@iconify-icons/ri/settings-3-line'
import riShieldUserLine from '@iconify-icons/ri/shield-user-line'
import riSpamFill from '@iconify-icons/ri/spam-fill'
import riSunLine from '@iconify-icons/ri/sun-line'
import riTableLine from '@iconify-icons/ri/table-line'
import riUserAddLine from '@iconify-icons/ri/user-add-line'
import riUserLine from '@iconify-icons/ri/user-line'
import riUserUnfollowLine from '@iconify-icons/ri/user-unfollow-line'
import { addIcon } from '@iconify/vue'

addIcon('ri:add-line', riAddLine)
addIcon('ri:alert-fill', riAlertFill)
addIcon('ri:alert-line', riAlertLine)
addIcon('ri:archive-line', riArchiveLine)
addIcon('ri:arrow-down-line', riArrowDownLine)
addIcon('ri:arrow-down-s-line', riArrowDownSLine)
addIcon('ri:arrow-left-double-line', riArrowLeftDoubleLine)
addIcon('ri:arrow-left-line', riArrowLeftLine)
addIcon('ri:arrow-left-right-line', riArrowLeftRightLine)
addIcon('ri:arrow-left-s-line', riArrowLeftSLine)
addIcon('ri:arrow-right-double-line', riArrowRightDoubleLine)
addIcon('ri:arrow-right-line', riArrowRightLine)
addIcon('ri:arrow-right-s-line', riArrowRightSLine)
addIcon('ri:arrow-up-line', riArrowUpLine)
addIcon('ri:arrow-up-s-line', riArrowUpSLine)
addIcon('ri:bookmark-line', riBookmarkLine)
addIcon('ri:briefcase-line', riBriefcaseLine)
addIcon('ri:calendar-line', riCalendarLine)
addIcon('ri:check-line', riCheckLine)
addIcon('ri:checkbox-circle-fill', riCheckboxCircleFill)
addIcon('ri:checkbox-circle-line', riCheckboxCircleLine)
addIcon('ri:close-circle-line', riCloseCircleLine)
addIcon('ri:close-line', riCloseLine)
addIcon('ri:compass-3-line', riCompass3Line)
addIcon('ri:dashboard-line', riDashboardLine)
addIcon('ri:delete-bin-line', riDeleteBinLine)
addIcon('ri:draggable', riDraggable)
addIcon('ri:edit-line', riEditLine)
addIcon('ri:error-warning-fill', riErrorWarningFill)
addIcon('ri:error-warning-line', riErrorWarningLine)
addIcon('ri:expand-up-down-line', riExpandUpDownLine)
addIcon('ri:external-link-line', riExternalLinkLine)
addIcon('ri:eye-line', riEyeLine)
addIcon('ri:file-copy-line', riFileCopyLine)
addIcon('ri:filter-3-line', riFilter3Line)
addIcon('ri:filter-line', riFilterLine)
addIcon('ri:flashlight-fill', riFlashlightFill)
addIcon('ri:government-line', riGovernmentLine)
addIcon('ri:group-line', riGroupLine)
addIcon('ri:home-line', riHomeLine)
addIcon('ri:inbox-2-line', riInbox2Line)
addIcon('ri:information-fill', riInformationFill)
addIcon('ri:information-line', riInformationLine)
addIcon('ri:layout-column-line', riLayoutColumnLine)
addIcon('ri:layout-grid-line', riLayoutGridLine)
addIcon('ri:lightbulb-line', riLightbulbLine)
addIcon('ri:list-check', riListCheck)
addIcon('ri:list-unordered', riListUnordered)
addIcon('ri:logout-box-r-line', riLogoutBoxRLine)
addIcon('ri:mail-line', riMailLine)
addIcon('ri:map-pin-2-line', riMapPin2Line)
addIcon('ri:menu-line', riMenuLine)
addIcon('ri:moon-line', riMoonLine)
addIcon('ri:more-2-fill', riMore2Fill)
addIcon('ri:more-2-line', riMore2Line)
addIcon('ri:more-fill', riMoreFill)
addIcon('ri:notification-3-line', riNotification3Line)
addIcon('ri:pencil-line', riPencilLine)
addIcon('ri:price-tag-3-line', riPriceTag3Line)
addIcon('ri:refresh-line', riRefreshLine)
addIcon('ri:restart-line', riRestartLine)
addIcon('ri:search-line', riSearchLine)
addIcon('ri:settings-3-line', riSettings3Line)
addIcon('ri:shield-user-line', riShieldUserLine)
addIcon('ri:spam-fill', riSpamFill)
addIcon('ri:sun-line', riSunLine)
addIcon('ri:table-line', riTableLine)
addIcon('ri:user-add-line', riUserAddLine)
addIcon('ri:user-line', riUserLine)
addIcon('ri:user-unfollow-line', riUserUnfollowLine)
