# Generated by Django 6.0.2 on 2026-02-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [("shared", "0011_alter_offermodel_region")]

    dependencies = [
        ("referentiel", "0010_alter_offermodel_verse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offermodel",
            name="region",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
