# Generated by Django 6.0.2 on 2026-02-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [("shared", "0012_alter_vectorizeddocumentmodel_options_and_more")]

    dependencies = [
        ("referentiel", "0011_alter_offermodel_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concoursmodel",
            name="corps",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="concoursmodel",
            name="grade",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
