# Generated by Django 6.0.2 on 2026-02-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [("shared", "0015_corpsmodel_archived_at_corpsmodel_processed_at")]

    dependencies = [
        ("referentiel", "0014_concoursmodel_archived_at_concoursmodel_processed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpsmodel",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="corpsmodel",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
