# Generated by Django 6.0.2 on 2026-03-05 15:56

import django.contrib.postgres.indexes
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [("shared", "0018_alter_vectorizeddocumentmodel_options_and_more")]

    dependencies = [
        ("referentiel", "0017_populate_processed_at"),
    ]

    operations = []
