# Generated by Django 6.0.4 on 2026-04-13 09:02

from django.db import migrations


class Migration(migrations.Migration):
    replaces = [("shared", "0019_remove_vectorizeddocumentmodel_embedding_hnsw_idx_and_more")]

    dependencies = [
        ("referentiel", "0018_alter_vectorizeddocumentmodel_options_and_more"),
    ]

    operations = []
