# Generated by Django 6.0.4 on 2026-04-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [("shared", "0024_alter_metiermodel_code_emploi_csp")]

    dependencies = [
        ("referentiel", "0023_alter_metiermodel_external_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metiermodel",
            name="code_emploi_csp",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
