# Generated by Django 6.0.5 on 2026-05-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [("shared", "0026_offermodel_area")]

    dependencies = [
        ("referentiel", "0025_offermodel_code_emploi_csp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offermodel",
            name="area",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
