# Generated by Django 6.0.5 on 2026-05-19 15:20

from django.db import migrations


class Migration(migrations.Migration):
    replaces = [("shared", "0027_rename_code_domaine_fonctionnel_metiermodel_domaine_fonctionnel_code")]

    dependencies = [
        ("referentiel", "0026_offermodel_area"),
    ]

    operations = [
        migrations.RenameField(
            model_name="metiermodel",
            old_name="code_domaine_fonctionnel",
            new_name="domaine_fonctionnel_code",
        ),
    ]
