# Generated by Django 6.0.6 on 2026-06-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0036_fix_missing_id_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='application_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='conditions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='contacts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='contract_kind',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='criteria',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='complements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='employer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='job_vacancy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='location_label',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='long_title',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
