# Generated by Django 6.0.6 on 2026-07-01 10:36

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0037_offermodel_application_url_offermodel_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offermodel',
            name='conditions',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='offermodel',
            name='contacts',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='offermodel',
            name='contract_kind',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='offermodel',
            name='criteria',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
