# Generated by Django 6.0.7 on 2026-08-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0038_alter_offermodel_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='job_family_referential',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RunSQL(
            sql=(
                "UPDATE offers SET job_family_referential = 'RMFPv2' "
                "WHERE code_emploi_csp IS NOT NULL"
            ),
            reverse_sql=migrations.RunSQL.noop,
            elidable=True,
        ),
    ]
