# Generated by Django 6.0.7 on 2026-08-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0039_offermodel_job_family_referential'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='local_job_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
