# Generated by Django 6.0.7 on 2026-08-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0040_offermodel_local_job_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='functional_area_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
