# Generated by Django 6.1.1 on 2026-09-23 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0035_alter_talentsoftorganismemodel_organisme'),
        ('referentiel', '0042_populate_offer_functional_area_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='talentsoft_organisme_entity_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='ingestion.talentsoftorganismemodel', to_field='entity_code'),
        ),
    ]
