# Generated by Django 6.1.1 on 2026-10-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0045_remove_duplicate_corps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpsmodel',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
