# Generated by Django 6.1.1 on 2026-10-01 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0046_alter_corpsmodel_code'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='offermodel',
            name='offers_externa_91aec4_idx',
        ),
        migrations.RemoveField(
            model_name='offermodel',
            name='external_id',
        ),
    ]
