# Generated by Django 6.1.1 on 2026-10-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0047_remove_offermodel_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='application_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='exercise_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='service_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
