# Generated by Django 6.1.1 on 2026-10-06 14:58

from django.db import migrations, models

INITIALIZE_SEQUENCES_SQL = r"""
    INSERT INTO offer_reference_sequences (year, last_value)
    SELECT
        split_part(reference, '-', 2)::integer,
        max(split_part(reference, '-', 3)::integer)
    FROM offers
    WHERE reference ~ '^CSP-\d{4}-\d{6}$'
    GROUP BY 1
    ON CONFLICT (year) DO UPDATE
    SET last_value = greatest(
        offer_reference_sequences.last_value, EXCLUDED.last_value
    )
"""


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0050_rename_contract_type_offer_nature'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferReferenceSequenceModel',
            fields=[
                ('year', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('last_value', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': "Séquence de références d'offres",
                'verbose_name_plural': "Séquences de références d'offres",
                'db_table': 'offer_reference_sequences',
            },
        ),
        migrations.RunSQL(INITIALIZE_SEQUENCES_SQL, migrations.RunSQL.noop),
    ]
