# Generated by Django 6.1.1 on 2026-10-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0050_rename_contract_type_offer_nature'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferReferenceSequenceModel',
            fields=[
                ('year', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('last_value', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': "Séquence de références d'offres",
                'verbose_name_plural': "Séquences de références d'offres",
                'db_table': 'offer_reference_sequences',
            },
        ),
    ]
