# Generated by Django 6.1.1 on 2026-10-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0051_offer_reference_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='job_vacancy_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
