from datetime import datetime, timezone
from typing import List, Tuple, cast

from domain.entities.document import Document, DocumentType
from domain.gateways.document_gateway_interface import IDocumentGateway
from domain.services.async_http_client_interface import IAsyncHttpClient
from domain.services.logger_interface import ILogger
from domain.types import JsonDataType
from infrastructure.external_gateways.dtos.ingres_corps_dtos import (
    IngresCorpsApiResponse,
)
from infrastructure.external_gateways.dtos.ingres_metiers_dtos import (
    IngresMetiersApiResponse,
)
from infrastructure.external_gateways.talentsoft_client import (
    TalentsoftBackClient,
    TalentsoftFrontClient,
)

MAX_OFFSET = 100000


class ExternalDocumentGateway(IDocumentGateway):
    def __init__(
        self,
        piste_client: IAsyncHttpClient,
        talentsoft_front_client: TalentsoftFrontClient,
        talentsoft_back_client: TalentsoftBackClient,
        logger_service: ILogger,
    ):
        self.piste_client = piste_client
        self.talentsoft_front_client = talentsoft_front_client
        self.talentsoft_back_client = talentsoft_back_client
        self.logger = logger_service
        self._source = {
            DocumentType.CORPS: self._fetch_ingres_api,
            DocumentType.METIERS: self._fetch_ingres_api,
            DocumentType.OFFERS: self._fetch_talentsoft_front_api,
        }

    async def fetch_by_type(
        self, document_type: DocumentType, start: int = 1, batch_size: int = 1000
    ) -> Tuple[List[Document], bool]:
        self.logger.info("Fetching documents of type %s", document_type)

        source = self._source.get(document_type)
        if not source:
            raise ValueError(f"No fetch source for {document_type}")

        raw_documents, has_more = await source(document_type, start, batch_size)
        now = datetime.now(timezone.utc)

        documents = []

        if document_type == DocumentType.OFFERS:
            # For OFFERS, raw_documents is already a list of Document objects
            return cast(List[Document], raw_documents), has_more

        elif document_type == DocumentType.CORPS:
            typed_raw_documents = cast(List[dict], raw_documents)
            corps_response = IngresCorpsApiResponse.from_list(typed_raw_documents)

            for corps_doc in corps_response.documents:
                document = Document(
                    external_id=str(corps_doc.identifiant),
                    raw_data=corps_doc.model_dump(),
                    type=document_type,
                    created_at=now,
                    # id will be auto-generated by Document entity
                )
                documents.append(document)

        elif document_type == DocumentType.METIERS:
            typed_raw_documents = cast(List[dict], raw_documents)
            metiers_response = IngresMetiersApiResponse.from_list(typed_raw_documents)

            for metiers_doc in metiers_response.documents:
                document = Document(
                    external_id=str(metiers_doc.identifiant),
                    raw_data=metiers_doc.model_dump(),
                    type=document_type,
                    created_at=now,
                    # id will be auto-generated by Document entity
                )
                documents.append(document)

        return documents, has_more

    async def _fetch_ingres_api(
        self, document_type: DocumentType, start: int = 1, batch_size: int = 1000
    ) -> Tuple[List[JsonDataType], bool]:
        document_type_map = {
            DocumentType.CORPS: "CORPS",
            DocumentType.METIERS: "RMFP_EMPL_REF",
        }

        endpoint = document_type_map.get(document_type)
        if endpoint is None:
            raise ValueError(f"Ingres: unknown document type: {document_type}")

        async with self.piste_client:
            response = await self.piste_client.get(
                endpoint, params={"enVigueur": "true", "full": "true"}
            )

        response_data = response.json()
        if not isinstance(response_data, dict) or "items" not in response_data:
            raise ValueError(f"Invalid API response format: {response_data}")

        raw_documents = response_data["items"]
        if not isinstance(raw_documents, list):
            raise ValueError(f"Expected list of documents, got {type(raw_documents)}")

        self.logger.info("Found %d documents", len(raw_documents))

        has_more = False
        return cast(List[JsonDataType], raw_documents), has_more

    async def _fetch_talentsoft_front_api(
        self, document_type: DocumentType, start: int = 1, batch_size: int = 1000
    ) -> Tuple[List[Document], bool]:
        if document_type != DocumentType.OFFERS:
            raise ValueError(
                f"Talentsoft Front API: unsupported document type: {document_type}"
            )

        # Manage connection at client level for better performance
        async with self.talentsoft_front_client:
            try:
                raw_documents, has_more = await self.talentsoft_front_client.get_all(
                    start=start, count=batch_size
                )
            except Exception as e:
                self.logger.error("Failed to fetch offers from Talentsoft: %s", e)
                return [], False

            self.logger.info(
                "Found %d offers from Talentsoft Front API", len(raw_documents)
            )

            now = datetime.now(timezone.utc)
            documents = []

            for raw_doc in raw_documents:
                reference = raw_doc.reference
                if reference is None:
                    self.logger.warning(
                        "Skipping raw_doc without reference: %s", raw_doc
                    )
                    continue

                versant_code_obj = raw_doc.salaryRange
                versant = versant_code_obj.clientCode if versant_code_obj else "UNK"

                external_id = f"{versant}-{reference}"

                document = Document(
                    external_id=external_id,
                    raw_data=raw_doc.model_dump(),
                    type=document_type,
                    created_at=now,
                    # id will be auto-generated by Document entity
                )
                documents.append(document)

            return documents, has_more

    async def get_detail(
        self, document_type: DocumentType, external_id: str
    ) -> Document:
        if document_type != DocumentType.OFFERS:
            raise ValueError(
                f"Talentsoft Front API: unsupported document type: {document_type}"
            )

        # external_id format is "{versant}-{reference}", e.g. "FPE-12345"
        # The reference is everything after the first "-"
        reference = external_id.split("-", 1)[-1]

        async with self.talentsoft_front_client:
            try:
                raw_doc = await self.talentsoft_front_client.get_detail(reference)
            except Exception as e:
                self.logger.error(
                    "Failed to fetch detail %s %s: %s", document_type, external_id, e
                )
                raise
            now = datetime.now(timezone.utc)
            return Document(
                external_id=external_id,
                raw_data=raw_doc.model_dump(),
                type=document_type,
                created_at=now,
            )

    async def get_archived_documents_by_period(
        self,
        updated_after: datetime,
    ) -> List[str]:
        offset: int | None = 0
        external_ids = []

        async with self.talentsoft_back_client:
            while offset is not None and offset < MAX_OFFSET:
                try:
                    (
                        raw_documents,
                        offset,
                    ) = await self.talentsoft_back_client.get_vacancies(
                        update_date=updated_after,
                        date_operator="gt",
                        offset=offset,
                    )
                except Exception as e:
                    self.logger.error("Failed to fetch offers from Talentsoft: %s", e)
                    return []

                self.logger.info(
                    "Found %d offers from Talentsoft Back API",
                    len(raw_documents),
                )

                if not raw_documents:
                    break

                for raw_doc in raw_documents:
                    reference = raw_doc.reference
                    if reference is None:
                        self.logger.warning(
                            "Skipping raw_doc without reference: %s", raw_doc
                        )
                        continue

                    versant_code_obj = raw_doc.salaryRange
                    versant = versant_code_obj.id if versant_code_obj.id else "UNK"

                    external_ids.append(f"{versant}-{reference}")

            return external_ids
