# Generated by Django 6.1.1 on 2026-09-29 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidate", "0011_documentmodel"),
        ("users", "0009_lowercase_emails"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("objet", models.CharField(max_length=255)),
                (
                    "candidature",
                    models.ForeignKey(
                        db_column="candidature_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversations",
                        to="candidate.candidaturemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "db_table": "conversation",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("objet", ""), _negated=True),
                        name="conversation_objet_non_vide",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MessageModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contenu", models.TextField()),
                (
                    "auteur",
                    models.ForeignKey(
                        db_column="auteur_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages_rediges",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="messagerie.conversationmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "message",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("contenu", ""), _negated=True),
                        name="message_contenu_non_vide",
                    )
                ],
                "indexes": [
                    models.Index(
                        fields=["conversation", "created_at"],
                        name="message_conv_created_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MessageDocumentModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="piece_jointe",
                        to="candidate.documentmodel",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pieces_jointes",
                        to="messagerie.messagemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce jointe de message",
                "verbose_name_plural": "Pièces jointes de message",
                "db_table": "message_document",
            },
        ),
        migrations.CreateModel(
            name="ConversationLectureModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("read_at", models.DateTimeField()),
                (
                    "utilisateur",
                    models.ForeignKey(
                        db_column="utilisateur_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lectures_conversations",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lectures",
                        to="messagerie.conversationmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lecture de conversation",
                "verbose_name_plural": "Lectures de conversation",
                "db_table": "conversation_lecture",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("conversation", "utilisateur"),
                        name="conversation_lecture_unique",
                    )
                ],
            },
        ),
    ]
