# Generated by Django 5.2.7 on 2025-12-15 19:19

import django.contrib.postgres.fields
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorpsModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=10, null=True)),
                ('ministry', models.CharField(max_length=100)),
                ('diploma_level', models.IntegerField(blank=True, null=True)),
                ('short_label', models.CharField(max_length=200)),
                ('long_label', models.TextField()),
                ('access_modalities', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Corps',
                'verbose_name_plural': 'Corps',
                'db_table': 'corps',
            },
        ),
        migrations.CreateModel(
            name='VectorizedDocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.IntegerField(db_index=True, unique=True)),
                ('document_type', models.CharField(choices=[('CORPS', 'CORPS'), ('GRADE', 'GRADE'), ('CONCOURS', 'CONCOURS'), ('CONCOURS_LAW', 'CONCOURS_LAW'), ('CONCOURS_LAW_DETAILS', 'CONCOURS_LAW_DETAILS')], db_index=True, max_length=20)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=3072)),
                ('metadata', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vectorized_documents',
            },
        ),
        migrations.CreateModel(
            name='ConcoursModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('corps_id', models.IntegerField()),
                ('nor_original', models.CharField(max_length=50)),
                ('nor_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('category', models.CharField(max_length=20)),
                ('ministry', models.CharField(max_length=100)),
                ('access_modality', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('written_exam_date', models.DateTimeField(blank=True, null=True)),
                ('open_position_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Concours',
                'verbose_name_plural': 'Concours',
                'db_table': 'concours',
                'indexes': [models.Index(fields=['corps_id'], name='concours_corps_i_871a7f_idx'), models.Index(fields=['nor_original'], name='concours_nor_ori_fd92de_idx')],
            },
        ),
    ]
