# Generated by Django 5.2.7 on 2025-12-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='concoursmodel',
            name='concours_corps_i_871a7f_idx',
        ),
        migrations.RemoveField(
            model_name='concoursmodel',
            name='corps_id',
        ),
        migrations.AddField(
            model_name='concoursmodel',
            name='corps',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='concoursmodel',
            name='grade',
            field=models.CharField(default='', max_length=200),
        ),
    ]
