# Generated by Django 5.2.7 on 2026-01-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vectorizeddocumentmodel",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("CORPS", "CORPS"),
                    ("GRADE", "GRADE"),
                    ("CONCOURS", "CONCOURS"),
                    ("CONCOURS_LAW", "CONCOURS_LAW"),
                    ("CONCOURS_LAW_DETAILS", "CONCOURS_LAW_DETAILS"),
                    ("OFFERS", "OFFERS"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OfferModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("external_id", models.CharField(max_length=100, unique=True)),
                ("verse", models.CharField(max_length=20)),
                ("titre", models.CharField(max_length=500)),
                ("profile", models.TextField()),
                ("category", models.CharField(max_length=20)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("limit_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Offer",
                "verbose_name_plural": "Offers",
                "db_table": "offers",
                "indexes": [
                    models.Index(
                        fields=["external_id"], name="offers_externa_91aec4_idx"
                    )
                ],
            },
        ),
    ]
