# Generated by Django 5.2.10 on 2026-01-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0006_rename_limit_date_offermodel_beginning_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offermodel",
            name="mission",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="offermodel",
            name="organization",
            field=models.CharField(max_length=500),
        ),
    ]
