# Generated by Django 5.2.10 on 2026-01-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0009_remove_publication_date_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offermodel",
            name="verse",
            field=models.CharField(
                blank=True,
                choices=[("FPT", "FPT"), ("FPE", "FPE"), ("FPH", "FPH")],
                max_length=20,
                null=True,
            ),
        ),
    ]
