# Generated by Django 6.0.2 on 2026-02-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0011_alter_offermodel_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corpsmodel",
            name="category",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="corpsmodel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
