# Generated by Django 6.0.2 on 2026-02-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0011_alter_offermodel_region"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vectorizeddocumentmodel",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "VectorizedDocument",
                "verbose_name_plural": "VectorizedDocuments",
            },
        ),
        migrations.AlterField(
            model_name="concoursmodel",
            name="corps",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="concoursmodel",
            name="grade",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddConstraint(
            model_name="vectorizeddocumentmodel",
            constraint=models.UniqueConstraint(
                fields=("id", "document_type"), name="unique_id_document_type"
            ),
        ),
    ]
