# Generated by Django 6.0.2 on 2026-02-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0012_alter_corpsmodel_category_alter_corpsmodel_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vectorizeddocumentmodel",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "VectorizedDocument",
                "verbose_name_plural": "VectorizedDocuments",
            },
        ),
        migrations.AlterField(
            model_name="vectorizeddocumentmodel",
            name="document_id",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddConstraint(
            model_name="vectorizeddocumentmodel",
            constraint=models.UniqueConstraint(
                fields=("id", "document_type"), name="unique_id_document_type"
            ),
        ),
    ]
