# Generated by Django 6.0.2 on 2026-02-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0012_alter_vectorizeddocumentmodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offermodel",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="offermodel",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
