# Generated by Django 6.0.2 on 2026-02-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0013_offermodel_archived_at_offermodel_processed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="concoursmodel",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="concoursmodel",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
