# Generated by Django 6.0.2 on 2026-02-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0015_corpsmodel_archived_at_corpsmodel_processed_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vectorizeddocumentmodel",
            name="unique_id_document_type",
        ),
        migrations.AddConstraint(
            model_name="vectorizeddocumentmodel",
            constraint=models.UniqueConstraint(
                fields=("entity_id", "document_type"), name="unique_id_document_type"
            ),
        ),
    ]
