# Generated by Django 6.0.2 on 2026-02-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0015_corpsmodel_archived_at_corpsmodel_processed_at"),
    ]

    operations = []
