# Generated by Django 6.0.2 on 2026-02-23 14:11

from django.db import migrations

def populate_processed_at(apps, schema_editor):
    from django.db.models import OuterRef, Subquery

    VectorizedDocumentModel = apps.get_model("shared", "VectorizedDocumentModel")

    for model_name, document_type in [
        ("ConcoursModel","CONCOURS"),
        ("CorpsModel","CORPS"),
        ("OfferModel","OFFERS")
    ]:
        model = apps.get_model("shared",model_name)
        model.objects.update(
            processed_at=Subquery(
                VectorizedDocumentModel.objects.filter(
                    document_type=document_type,
                    entity_id=OuterRef("id")
                ).values("updated_at")[:1]
            )
        )

class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0016_remove_vectorizeddocumentmodel_unique_id_document_type_and_more"),
    ]

    operations = [
        migrations.RunPython(
            populate_processed_at,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        )
    ]
