# Generated by Django 6.0.2 on 2026-02-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0016_remove_vectorizeddocumentmodel_unique_id_document_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="concoursmodel",
            name="processing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="corpsmodel",
            name="processing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="offermodel",
            name="processing",
            field=models.BooleanField(default=False),
        ),

    ]
