# Generated by Django 6.0.4 on 2026-04-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0018_alter_vectorizeddocumentmodel_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="vectorizeddocumentmodel",
            name="embedding_hnsw_idx",
        ),
        migrations.RemoveIndex(
            model_name="vectorizeddocumentmodel",
            name="doc_type_entity_idx",
        ),
        migrations.RemoveConstraint(
            model_name="vectorizeddocumentmodel",
            name="unique_id_document_type",
        ),
        migrations.DeleteModel(
            name="VectorizedDocumentModel",
        ),
    ]
