# Generated by Django 6.0.4 on 2026-04-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0019_remove_vectorizeddocumentmodel_embedding_hnsw_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetierModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("external_id", models.CharField(max_length=50, unique=True)),
                (
                    "code_emploi_csp",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "libelle_emploi_csp",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "referenciel_metier_id",
                    models.CharField(
                        blank=True,
                        choices=[("RMFP_V1", "RMFP_V1")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("libelle_court", models.CharField(max_length=200)),
                ("libelle_long", models.CharField(max_length=500)),
                ("definition_synthetique", models.TextField(blank=True, null=True)),
                ("code_domaine_fonctionnel", models.CharField(max_length=20)),
                ("libelle_domaine_fonctionnel", models.CharField(max_length=200)),
                ("code_famille", models.CharField(max_length=20)),
                ("libelle_famille", models.CharField(max_length=200)),
                (
                    "versants",
                    models.CharField(
                        blank=True,
                        choices=[("FPT", "FPT"), ("FPE", "FPE"), ("FPH", "FPH")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("conditions_particulieres", models.TextField(blank=True, null=True)),
                (
                    "competences_specifiques_fpe",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "competences_specifiques_fpt",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "competences_specifiques_fph",
                    models.TextField(blank=True, null=True),
                ),
                ("activites", models.JSONField(default=list)),
                ("competences", models.JSONField(default=list)),
                ("processing", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Métier",
                "verbose_name_plural": "Métiers",
                "db_table": "metiers",
                "indexes": [
                    models.Index(
                        fields=["external_id"], name="metiers_externa_310f85_idx"
                    ),
                    models.Index(
                        fields=["code_emploi_csp"], name="metiers_code_em_696178_idx"
                    ),
                ],
            },
        ),
    ]
