# Generated by Django 6.0.4 on 2026-04-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0020_create_metiers_table"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="metiermodel",
            name="metiers_externa_310f85_idx",
        ),
        migrations.RemoveIndex(
            model_name="metiermodel",
            name="metiers_code_em_696178_idx",
        ),
        migrations.AlterField(
            model_name="metiermodel",
            name="code_domaine_fonctionnel",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="metiermodel",
            name="code_famille",
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name="metiermodel",
            name="competences",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="metiermodel",
            name="conditions_particulieres",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="metiermodel",
            name="external_id",
            field=models.CharField(default="", max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name="metiermodel",
            name="versants",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddIndex(
            model_name="metiermodel",
            index=models.Index(
                fields=["external_id", "code_emploi_csp"],
                name="metiers_externa_48dda8_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="metiermodel",
            name="competences_specifiques_fpe",
        ),
        migrations.RemoveField(
            model_name="metiermodel",
            name="competences_specifiques_fph",
        ),
        migrations.RemoveField(
            model_name="metiermodel",
            name="competences_specifiques_fpt",
        ),
    ]
