# Generated by Django 6.0.4 on 2026-04-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0022_remove_metiermodel_competences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metiermodel",
            name="external_id",
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
