# Generated by Django 6.0.4 on 2026-05-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0024_alter_metiermodel_code_emploi_csp"),
    ]

    operations = [
        migrations.AddField(
            model_name="offermodel",
            name="code_emploi_csp",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
