# Generated by Django 6.0.5 on 2026-05-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("shared", "0025_offermodel_code_emploi_csp"),
        ("shared", "0026_increase_code_famille_length"),
        ("shared", "0027_remove_metiermodel_metiers_externa_48dda8_idx_and_more"),
    ]

    dependencies = [
        ("shared", "0024_alter_metiermodel_code_emploi_csp"),
    ]

    operations = [
        migrations.AddField(
            model_name="offermodel",
            name="code_emploi_csp",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="metiermodel",
            name="code_famille",
            field=models.CharField(max_length=8),
        ),
        migrations.RemoveIndex(
            model_name="metiermodel",
            name="metiers_externa_48dda8_idx",
        ),
        migrations.AddField(
            model_name="metiermodel",
            name="offer_family_code",
            field=models.CharField(default="", max_length=8),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="metiermodel",
            index=models.Index(
                fields=["external_id"], name="metiers_externa_310f85_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="metiermodel",
            name="code_emploi_csp",
        ),
        migrations.RemoveField(
            model_name="metiermodel",
            name="code_famille",
        ),
        migrations.RemoveField(
            model_name="metiermodel",
            name="libelle_court",
        ),
        migrations.RemoveField(
            model_name="metiermodel",
            name="libelle_domaine_fonctionnel",
        ),
        migrations.RemoveField(
            model_name="metiermodel",
            name="libelle_emploi_csp",
        ),
        migrations.RemoveField(
            model_name="metiermodel",
            name="libelle_famille",
        ),
        migrations.RemoveField(
            model_name="metiermodel",
            name="referenciel_metier_id",
        ),
    ]
