# Generated by Django 6.0.4 on 2026-05-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0025_offermodel_code_emploi_csp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metiermodel",
            name="code_famille",
            field=models.CharField(max_length=8),
        ),
    ]
