# Generated by Django 6.0.6 on 2026-06-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrganismeModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=255)),
                (
                    "versant",
                    models.CharField(
                        choices=[("FPT", "FPT"), ("FPE", "FPE"), ("FPH", "FPH")],
                        max_length=10,
                    ),
                ),
                ("siret", models.CharField(max_length=14, unique=True)),
                ("parent_id", models.UUIDField(blank=True, null=True)),
                ("localisation", models.JSONField(blank=True, null=True)),
                (
                    "etapes",
                    models.JSONField(
                        blank=True,
                        help_text="Ordered recruitment steps. Each item: {'entity_id': str, 'categorie': str, 'nom': str}",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisme",
                "verbose_name_plural": "Organismes",
                "db_table": "organisme",
            },
        ),
    ]
