# Generated by Django 6.0.6 on 2026-06-25 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0005_fix_cv_metadata_id_index"),
        ("recruteur", "0001_initial"),
        ("users", "0007_merge_20260612_1624"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.TextField()),
                ("supprimee_le", models.DateTimeField(blank=True, null=True)),
                (
                    "candidature",
                    models.ForeignKey(
                        db_column="candidature_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notes",
                        to="candidate.candidaturemodel",
                    ),
                ),
                (
                    "mis_a_jour_par",
                    models.ForeignKey(
                        db_column="mis_a_jour_par_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notes_modifiees",
                        to="users.profilagentmodel",
                        to_field="utilisateur_id",
                    ),
                ),
                (
                    "publie_par",
                    models.ForeignKey(
                        db_column="publie_par_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notes_publiees",
                        to="users.profilagentmodel",
                        to_field="utilisateur_id",
                    ),
                ),
                (
                    "supprimee_par",
                    models.ForeignKey(
                        blank=True,
                        db_column="supprimee_par_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notes_supprimees",
                        to="users.profilagentmodel",
                        to_field="utilisateur_id",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
                "db_table": "note",
            },
        ),
    ]
