# Generated by Django 6.0.6 on 2026-06-26 17:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruteur', '0001_initial'),
        ('users', '0007_merge_20260612_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecrutementModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('offre_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('actif', 'actif'), ('archive', 'archive')], db_index=True, default='actif', max_length=20)),
                ('etapes', models.JSONField(default=list, help_text="[{'entity_id': str, 'categorie': str, 'nom': str}, ...]")),
                ('positions', models.JSONField(default=list, help_text="[{'candidature_id': str, 'etape_id': str, 'ordre': int|null}, ...]")),
                ('responsables_ids', models.JSONField(default=list, help_text='[str(uuid), ...]')),
                ('candidat_recrute', models.ForeignKey(blank=True, db_column='candidat_recrute_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.profilcandidatmodel', to_field='utilisateur_id')),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recrutements', to='recruteur.organismemodel')),
            ],
            options={
                'verbose_name': 'Recrutement',
                'verbose_name_plural': 'Recrutements',
                'db_table': 'recrutement',
            },
        ),
    ]
