# Generated by Django 6.0.6 on 2026-07-08 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruteur', '0002_notemodel'),
        ('referentiel', '0038_alter_offermodel_conditions_and_more'),
        ('users', '0007_merge_20260612_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecrutementModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offre', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='recrutement', serialize=False, to='referentiel.offermodel')),
                ('ordre_etapes', models.JSONField(help_text="Liste ordonnée des UUID d'étapes (str) — ordre d'affichage Kanban uniquement. L'appartenance réelle est portée par EtapeModel.recrutement (FK), jamais par ce champ.")),
                ('organisme', models.ForeignKey(db_column='organisme_id', on_delete=django.db.models.deletion.PROTECT, related_name='recrutements', to='recruteur.organismemodel')),
            ],
            options={
                'verbose_name': 'Recrutement',
                'verbose_name_plural': 'Recrutements',
                'db_table': 'recrutement',
            },
        ),
        migrations.CreateModel(
            name='EtapeModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.CharField(choices=[('entree', 'entree'), ('en_cours', 'en_cours'), ('refus', 'refus'), ('accepte', 'accepte')], max_length=20)),
                ('nom', models.CharField(max_length=255)),
                ('ordre_candidatures', models.JSONField(blank=True, help_text="Liste ordonnée des UUID de candidatures (str) — ordre d'affichage au sein de cette étape uniquement. L'appartenance réelle est portée par CandidatureModel.etape (FK), jamais par ce champ.", null=True)),
                ('recrutement', models.ForeignKey(db_column='recrutement_id', on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='recruteur.recrutementmodel')),
            ],
            options={
                'verbose_name': 'Étape de recrutement',
                'verbose_name_plural': 'Étapes de recrutement',
                'db_table': 'etape_recrutement',
            },
        ),
        migrations.CreateModel(
            name='RecrutementAgentModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(db_column='agent_id', on_delete=django.db.models.deletion.PROTECT, related_name='recrutements_agents', to='users.profilagentmodel', to_field='utilisateur_id')),
                ('recrutement', models.ForeignKey(db_column='recrutement_id', on_delete=django.db.models.deletion.CASCADE, related_name='responsables_liaisons', to='recruteur.recrutementmodel')),
            ],
            options={
                'verbose_name': 'Agent de recrutement',
                'verbose_name_plural': 'Agents de recrutement',
                'db_table': 'recrutement_agent',
                'constraints': [models.UniqueConstraint(fields=('recrutement_id', 'agent_id'), name='unique_recrutement_agent')],
            },
        ),
    ]
