# Generated by Django 6.0.6 on 2026-07-16 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruteur', '0003_recrutement_etapes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recrutementagentmodel',
            name='recrutement',
            field=models.ForeignKey(db_column='recrutement_id', on_delete=django.db.models.deletion.CASCADE, related_name='agents_liaisons', to='recruteur.recrutementmodel'),
        ),
    ]
