# Generated by Django 6.0.7 on 2026-07-20 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruteur", "0004_alter_recrutementagentmodel_recrutement"),
        ("users", "0007_merge_20260612_1624"),
    ]

    operations = [
        migrations.AddField(
            model_name="recrutementagentmodel",
            name="role",
            field=models.CharField(
                choices=[
                    ("responsable", "responsable"),
                    ("recruteur", "recruteur"),
                    ("contributeur", "contributeur"),
                ],
                default="contributeur",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OrganismeAgentModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("responsable", "responsable"), ("membre", "membre")],
                        default="membre",
                        max_length=20,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        db_column="agent_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organismes_agents",
                        to="users.profilagentmodel",
                        to_field="utilisateur_id",
                    ),
                ),
                (
                    "organisme",
                    models.ForeignKey(
                        db_column="organisme_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents_liaisons",
                        to="recruteur.organismemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent d'organisme",
                "verbose_name_plural": "Agents d'organisme",
                "db_table": "organisme_agent",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisme_id", "agent_id"),
                        name="unique_organisme_agent",
                    )
                ],
            },
        ),
    ]
