# Generated by Django 6.0.7 on 2026-08-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recruteur", "0005_recrutementagentmodel_role_organismeagentmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="organismemodel",
            name="external_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="organismemodel",
            name="referentiel",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="organismemodel",
            name="millesime",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="organismemodel",
            name="gestion_ats",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="organismemodel",
            name="date_creation",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organismemodel",
            name="date_derniere_activite",
            field=models.DateField(blank=True, null=True),
        ),
    ]
