# Generated by Django 6.1 on 2026-08-19 14:05

import django.db.models.deletion
from django.db import migrations, models


def _drop_pattern_ops_index_sql(table: str, column: str) -> str:
    return f"""
        DO $$
        DECLARE
            idx_name text;
        BEGIN
            SELECT ic.relname INTO idx_name
            FROM pg_index ix
            JOIN pg_class ic ON ic.oid = ix.indexrelid
            JOIN pg_class tc ON tc.oid = ix.indrelid
            JOIN pg_attribute a ON a.attrelid = tc.oid AND a.attnum = ANY(ix.indkey)
            JOIN pg_opclass oc ON oc.oid = ANY(ix.indclass)
            WHERE tc.relname = '{table}'
              AND a.attname = '{column}'
              AND oc.opcname IN ('varchar_pattern_ops', 'text_pattern_ops')
            LIMIT 1;

            IF idx_name IS NOT NULL THEN
                EXECUTE format('DROP INDEX IF EXISTS %I', idx_name);
            END IF;
        END $$;
    """  # noqa: S608


class Migration(migrations.Migration):
    dependencies = [
        (
            "recruteur",
            "0006_organismemodel_external_id_organismemodel_millesime_and_more",
        ),
        ("users", "0008_alter_usermodel_username"),
    ]

    operations = [
        migrations.RunSQL(
            _drop_pattern_ops_index_sql("note", "publie_par_id"),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="notemodel",
            name="publie_par",
            field=models.ForeignKey(
                db_column="publie_par_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notes_publiees",
                to="users.profilagentmodel",
                to_field="utilisateur_id",
            ),
        ),
        migrations.RunSQL(
            _drop_pattern_ops_index_sql("organisme_agent", "agent_id"),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="organismeagentmodel",
            name="agent",
            field=models.ForeignKey(
                db_column="agent_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organismes_agents",
                to="users.profilagentmodel",
                to_field="utilisateur_id",
            ),
        ),
        migrations.RunSQL(
            _drop_pattern_ops_index_sql("recrutement_agent", "agent_id"),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="recrutementagentmodel",
            name="agent",
            field=models.ForeignKey(
                db_column="agent_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recrutements_agents",
                to="users.profilagentmodel",
                to_field="utilisateur_id",
            ),
        ),
    ]
