# Generated by Django 6.1 on 2026-08-19 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recruteur", "0007_alter_notemodel_publie_par_and_more"),
        ("users", "0008_alter_usermodel_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notemodel",
            name="publie_par",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notes_publiees",
                to="users.profilagentmodel",
                to_field="utilisateur_id",
            ),
        ),
        migrations.AlterField(
            model_name="organismeagentmodel",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organismes_agents",
                to="users.profilagentmodel",
                to_field="utilisateur_id",
            ),
        ),
        migrations.AlterField(
            model_name="recrutementagentmodel",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recrutements_agents",
                to="users.profilagentmodel",
                to_field="utilisateur_id",
            ),
        ),
    ]
