# Generated by Django 6.1 on 2026-08-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruteur", "0008_alter_notemodel_publie_par_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organismeagentmodel",
            name="date_revocation",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
