# Generated by Django 6.1 on 2026-09-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruteur", "0009_organismeagentmodel_date_revocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organismemodel",
            name="date_creation",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organismemodel",
            name="date_derniere_activite",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
