# Generated by Django 6.1.1 on 2026-09-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruteur", "0010_alter_organismemodel_date_creation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recrutementagentmodel",
            name="date_revocation",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
