# Generated by Django 6.1 on 2026-09-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruteur', '0010_alter_organismemodel_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organismeagentmodel',
            name='role',
            field=models.CharField(choices=[('superviseur', 'superviseur'), ('membre', 'membre')], default='membre', max_length=20),
        ),
    ]
