# Generated by Django 6.1.1 on 2026-09-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruteur', '0010_alter_organismemodel_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismemodel',
            name='supprime_le',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
