# Generated by Django 6.1.1 on 2026-09-15 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruteur', '0011_organisme_soft_delete'),
        ('recruteur', '0011_recrutementagentmodel_date_revocation'),
    ]

    operations = [
    ]
