# Generated by Django 6.1.1 on 2026-09-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruteur', '0012_alter_organismeagentmodel_role'),
        ('recruteur', '0012_merge_20260915_0936'),
    ]

    operations = [
    ]
