/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/recruteur/candidature/{candidature_uuid}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des notes d'une candidature */
        get: operations["recruteur_candidature_notes_list"];
        put?: never;
        /** Ajouter une note à une candidature */
        post: operations["recruteur_candidature_notes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruteur/candidature/{candidature_uuid}/notes/{note_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Supprimer une note d'une candidature */
        delete: operations["recruteur_candidature_notes_destroy"];
        options?: never;
        head?: never;
        /** Modifier une note d'une candidature */
        patch: operations["recruteur_candidature_notes_partial_update"];
        trace?: never;
    };
    "/recruteur/organisme/{organisme_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail d'un organisme */
        get: operations["recruteur_organisme_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruteur/organisme/{organisme_uuid}/parametres/etapes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des étapes de recrutement d'un organisme */
        get: operations["recruteur_organisme_parametres_etapes_list"];
        /** Modifier les étapes de recrutement d'un organisme */
        put: operations["recruteur_organisme_parametres_etapes_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruteur/organisme/{organisme_uuid}/parametres/etapes/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initialiser les étapes de recrutement par défaut d'un organisme */
        post: operations["recruteur_organisme_parametres_etapes_init_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruteur/organisme/{organisme_uuid}/recrutements-actifs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liste des recrutements actifs d'un organisme
         * @description Retourne la liste paginée des recrutements d'un organisme.
         */
        get: operations["recruteur_organisme_recrutements_actifs_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruteur/organisme/{organisme_uuid}/recrutements-archives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liste des recrutements archivés d'un organisme
         * @description Retourne la liste paginée des recrutements archivés d'un organisme.
         */
        get: operations["recruteur_organisme_recrutements_archives_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruteur/organisme/{organisme_uuid}/recrutements/{recrutement_uuid}/kanban": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Détail d'un recrutement — vue kanban */
        get: operations["recruteur_organisme_recrutements_kanban_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruteur/organisme/{organisme_uuid}/recrutements/{recrutement_uuid}/liste": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Détail d'un recrutement — vue liste (paginée) */
        get: operations["recruteur_organisme_recrutements_liste_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/utilisateur/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail de l'utilisateur connecté */
        get: operations["utilisateur_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {unknown} */
        BlankEnum: "";
        Candidat: {
            /** Format: uuid */
            uuid: string;
            nom: string;
            prenom: string;
        };
        Candidature: {
            /** Format: uuid */
            uuid: string;
            /** Format: date-time */
            date_soumission: string;
            /** Format: date-time */
            date_derniere_activite: string;
            candidat: components["schemas"]["Candidat"];
        };
        CandidatureListe: {
            /** Format: uuid */
            uuid: string;
            /** Format: date-time */
            date_soumission: string;
            candidat: components["schemas"]["Candidat"];
            /** Format: date-time */
            date_derniere_activite: string;
            etape: components["schemas"]["EtapeRecrutement"];
        };
        CandidaturesActives: {
            total: number | null;
            a_traiter: number | null;
            en_cours: number | null;
        };
        /**
         * @description * `ENTREE` - entree
         *     * `EN_COURS` - en_cours
         *     * `REFUS` - refus
         *     * `ACCEPTE` - accepte
         * @enum {string}
         */
        CategorieEnum: "ENTREE" | "EN_COURS" | "REFUS" | "ACCEPTE";
        /**
         * @description * `APLUS` - APLUS
         *     * `A` - A
         *     * `B` - B
         *     * `C` - C
         *     * `HORS_CATEGORIE` - HORS_CATEGORIE
         * @enum {string}
         */
        CategorieOffreEnum: "APLUS" | "A" | "B" | "C" | "HORS_CATEGORIE";
        CreerNote: {
            message: string;
        };
        /**
         * @description * `01` - 01
         *     * `02` - 02
         *     * `03` - 03
         *     * `04` - 04
         *     * `05` - 05
         *     * `06` - 06
         *     * `07` - 07
         *     * `08` - 08
         *     * `09` - 09
         *     * `10` - 10
         *     * `11` - 11
         *     * `12` - 12
         *     * `13` - 13
         *     * `14` - 14
         *     * `15` - 15
         *     * `16` - 16
         *     * `17` - 17
         *     * `18` - 18
         *     * `19` - 19
         *     * `21` - 21
         *     * `22` - 22
         *     * `23` - 23
         *     * `24` - 24
         *     * `25` - 25
         *     * `26` - 26
         *     * `27` - 27
         *     * `28` - 28
         *     * `29` - 29
         *     * `2A` - 2A
         *     * `2B` - 2B
         *     * `30` - 30
         *     * `31` - 31
         *     * `32` - 32
         *     * `33` - 33
         *     * `34` - 34
         *     * `35` - 35
         *     * `36` - 36
         *     * `37` - 37
         *     * `38` - 38
         *     * `39` - 39
         *     * `40` - 40
         *     * `41` - 41
         *     * `42` - 42
         *     * `43` - 43
         *     * `44` - 44
         *     * `45` - 45
         *     * `46` - 46
         *     * `47` - 47
         *     * `48` - 48
         *     * `49` - 49
         *     * `50` - 50
         *     * `51` - 51
         *     * `52` - 52
         *     * `53` - 53
         *     * `54` - 54
         *     * `55` - 55
         *     * `56` - 56
         *     * `57` - 57
         *     * `58` - 58
         *     * `59` - 59
         *     * `60` - 60
         *     * `61` - 61
         *     * `62` - 62
         *     * `63` - 63
         *     * `64` - 64
         *     * `65` - 65
         *     * `66` - 66
         *     * `67` - 67
         *     * `68` - 68
         *     * `69` - 69
         *     * `70` - 70
         *     * `71` - 71
         *     * `72` - 72
         *     * `73` - 73
         *     * `74` - 74
         *     * `75` - 75
         *     * `76` - 76
         *     * `77` - 77
         *     * `78` - 78
         *     * `79` - 79
         *     * `80` - 80
         *     * `81` - 81
         *     * `82` - 82
         *     * `83` - 83
         *     * `84` - 84
         *     * `85` - 85
         *     * `86` - 86
         *     * `87` - 87
         *     * `88` - 88
         *     * `89` - 89
         *     * `90` - 90
         *     * `91` - 91
         *     * `92` - 92
         *     * `93` - 93
         *     * `94` - 94
         *     * `95` - 95
         *     * `971` - 971
         *     * `972` - 972
         *     * `973` - 973
         *     * `974` - 974
         *     * `975` - 975
         *     * `976` - 976
         *     * `986` - 986
         *     * `987` - 987
         *     * `988` - 988
         *     * `SPM` - SPM
         *     * `WLF` - WLF
         * @enum {string}
         */
        DepartementEnum: "01" | "02" | "03" | "04" | "05" | "06" | "07" | 8 | 9 | "10" | "11" | "12" | "13" | "14" | "15" | "16" | "17" | "18" | "19" | "21" | "22" | "23" | "24" | "25" | "26" | "27" | "28" | "29" | "2A" | "2B" | "30" | "31" | "32" | "33" | "34" | "35" | "36" | "37" | "38" | "39" | "40" | "41" | "42" | "43" | "44" | "45" | "46" | "47" | "48" | "49" | "50" | "51" | "52" | "53" | "54" | "55" | "56" | "57" | "58" | "59" | "60" | "61" | "62" | "63" | "64" | "65" | "66" | "67" | "68" | "69" | "70" | "71" | "72" | "73" | "74" | "75" | "76" | "77" | "78" | "79" | "80" | "81" | "82" | "83" | "84" | "85" | "86" | "87" | "88" | "89" | "90" | "91" | "92" | "93" | "94" | "95" | "971" | "972" | "973" | "974" | "975" | "976" | "986" | "987" | "988" | "SPM" | "WLF";
        EtapeRecrutement: {
            /** Format: uuid */
            etape_uuid: string;
            nom: string;
            categorie: components["schemas"]["CategorieEnum"];
        };
        EtapeRecrutementDetailedCandidatures: {
            /** Format: uuid */
            etape_uuid: string;
            nom: string;
            categorie: components["schemas"]["CategorieEnum"];
            candidatures: components["schemas"]["Candidature"][];
        };
        GenericError: {
            error: string;
        };
        Localisation: {
            zone_geographique: components["schemas"]["ZoneGeographiqueEnum"];
            pays: string;
            region: components["schemas"]["RegionEnum"] | components["schemas"]["BlankEnum"];
            departement: components["schemas"]["DepartementEnum"] | components["schemas"]["BlankEnum"];
            localisation_label: string;
            /** Format: double */
            latitude: number | null;
            /** Format: double */
            longitude: number | null;
        };
        Note: {
            /** Format: uuid */
            entity_id: string;
            /** Format: uuid */
            candidature_id: string;
            message: string;
            /** Format: uuid */
            publie_par_id: string;
            publie_par_prenom: string;
            publie_par_nom: string;
            /** Format: date-time */
            publie_le: string;
        };
        NoteDetail: {
            /** Format: uuid */
            entity_id: string;
            /** Format: uuid */
            candidature_id: string;
            message: string;
            /** Format: uuid */
            publie_par_id: string;
        };
        /** @enum {unknown} */
        NullEnum: null;
        Organisme: {
            nom: string;
            siret: string;
        };
        PaginatedCandidatureListeResponse: {
            count: number;
            next: string | null;
            previous: string | null;
            results: components["schemas"]["CandidatureListe"][];
        };
        PaginatedRecrutementsActifsResponse: {
            count: number;
            next: string | null;
            previous: string | null;
            results: components["schemas"]["RecrutementsActifs"][];
        };
        PaginatedRecrutementsArchivesResponse: {
            count: number;
            next: string | null;
            previous: string | null;
            results: components["schemas"]["RecrutementsArchives"][];
        };
        PatchedEditerNote: {
            message?: string;
        };
        RecrutementDetailKanban: {
            /** Format: uuid */
            offer_id: string;
            intitule: string;
            /** Format: date-time */
            date_publication: string;
            localisation: components["schemas"]["Localisation"];
            organisme_recruteur: components["schemas"]["Organisme"];
            categorie_offre: components["schemas"]["CategorieOffreEnum"];
            etapes: components["schemas"]["EtapeRecrutementDetailedCandidatures"][];
        };
        RecrutementsActifs: {
            /** Format: uuid */
            offer_id: string;
            intitule: string;
            reference_csp: string;
            type_contrat: (components["schemas"]["TypeContratEnum"] | components["schemas"]["NullEnum"]) | null;
            responsables: components["schemas"]["Responsable"][];
            /** Format: date-time */
            date_publication: string;
            candidatures: components["schemas"]["CandidaturesActives"] | null;
            /** Format: date-time */
            derniere_activite: string;
        };
        RecrutementsArchives: {
            /** Format: uuid */
            offer_id: string;
            intitule: string;
            reference_csp: string;
            type_contrat: (components["schemas"]["TypeContratEnum"] | components["schemas"]["NullEnum"]) | null;
            responsables: components["schemas"]["Responsable"][];
            /** Format: date-time */
            date_archivage: string;
            finalise: boolean;
            recrute: string | null;
        };
        /**
         * @description * `01` - 01
         *     * `02` - 02
         *     * `03` - 03
         *     * `04` - 04
         *     * `06` - 06
         *     * `11` - 11
         *     * `24` - 24
         *     * `27` - 27
         *     * `28` - 28
         *     * `32` - 32
         *     * `44` - 44
         *     * `52` - 52
         *     * `53` - 53
         *     * `75` - 75
         *     * `76` - 76
         *     * `84` - 84
         *     * `93` - 93
         *     * `94` - 94
         *     * `DOM` - DOM
         *     * `TOM` - TOM
         * @enum {string}
         */
        RegionEnum: "01" | "02" | "03" | "04" | "06" | "11" | "24" | "27" | "28" | "32" | "44" | "52" | "53" | "75" | "76" | "84" | "93" | "94" | "DOM" | "TOM";
        Responsable: {
            nom: string;
        };
        TokenError: {
            detail: string;
            code: string;
            messages: components["schemas"]["TokenErrorMessage"][];
        };
        TokenErrorMessage: {
            token_class: string;
            token_type: string;
            message: string;
        };
        /**
         * @description * `TITULAIRE_CONTRACTUEL` - TITULAIRE_CONTRACTUEL
         *     * `CONTRACTUELS` - CONTRACTUELS
         *     * `TERRITORIAL` - TERRITORIAL
         * @enum {string}
         */
        TypeContratEnum: "TITULAIRE_CONTRACTUEL" | "CONTRACTUELS" | "TERRITORIAL";
        UpdateEtapeRecrutement: {
            /** Format: uuid */
            etape_uuid?: string;
            nom: string;
            categorie: components["schemas"]["CategorieEnum"];
        };
        Utilisateur: {
            /** Format: email */
            email: string;
            prenom: string;
            nom: string;
        };
        /**
         * @description * `AF` - AFRIQUE
         *     * `EU` - EUROPE
         *     * `AS` - ASIE
         *     * `AM` - AMERIQUE
         *     * `OC` - OCEANIE
         *     * `AN` - ANTARTIQUE
         * @enum {string}
         */
        ZoneGeographiqueEnum: "AF" | "EU" | "AS" | "AM" | "OC" | "AN";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    recruteur_candidature_notes_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidature_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
    recruteur_candidature_notes_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidature_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreerNote"];
                "application/x-www-form-urlencoded": components["schemas"]["CreerNote"];
                "multipart/form-data": components["schemas"]["CreerNote"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteDetail"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
    recruteur_candidature_notes_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidature_uuid: string;
                note_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
    recruteur_candidature_notes_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidature_uuid: string;
                note_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedEditerNote"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedEditerNote"];
                "multipart/form-data": components["schemas"]["PatchedEditerNote"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteDetail"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
    recruteur_organisme_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisme_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organisme"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
    recruteur_organisme_parametres_etapes_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisme_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtapeRecrutement"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
    recruteur_organisme_parametres_etapes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisme_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEtapeRecrutement"][];
                "application/x-www-form-urlencoded": components["schemas"]["UpdateEtapeRecrutement"][];
                "multipart/form-data": components["schemas"]["UpdateEtapeRecrutement"][];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtapeRecrutement"][];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
    recruteur_organisme_parametres_etapes_init_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisme_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtapeRecrutement"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
    recruteur_organisme_recrutements_actifs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisme_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRecrutementsActifsResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
    recruteur_organisme_recrutements_archives_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisme_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRecrutementsArchivesResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
    recruteur_organisme_recrutements_kanban_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisme_uuid: string;
                recrutement_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecrutementDetailKanban"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
    recruteur_organisme_recrutements_liste_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisme_uuid: string;
                recrutement_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCandidatureListeResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
    utilisateur_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Utilisateur"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
}
