/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/recruteur/organisme/{organisme_uuid}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail d'un organisme */
        get: operations["recruteur_organisme_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruteur/organisme/{organisme_uuid}/parametres/etapes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des étapes de recrutement d'un organisme */
        get: operations["recruteur_organisme_parametres_etapes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruteur/organisme/{organisme_uuid}/parametres/etapes/init/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initialiser les étapes de recrutement par défaut d'un organisme */
        post: operations["recruteur_organisme_parametres_etapes_init_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/utilisateur/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail de l'utilisateur connecté */
        get: operations["utilisateur_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `ENTREE` - entree
         *     * `EN_COURS` - en_cours
         *     * `TERMINALE` - terminale
         * @enum {string}
         */
        CategorieEnum: "ENTREE" | "EN_COURS" | "TERMINALE";
        EtapeRecrutement: {
            /** Format: uuid */
            etape_uuid: string;
            nom: string;
            categorie: components["schemas"]["CategorieEnum"];
        };
        GenericError: {
            error: string;
        };
        Organisme: {
            nom: string;
            siret: string;
        };
        TokenError: {
            detail: string;
            code: string;
            messages: components["schemas"]["TokenErrorMessage"][];
        };
        TokenErrorMessage: {
            token_class: string;
            token_type: string;
            message: string;
        };
        Utilisateur: {
            /** Format: email */
            email: string;
            prenom: string;
            nom: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    recruteur_organisme_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisme_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organisme"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
    recruteur_organisme_parametres_etapes_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisme_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtapeRecrutement"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
    recruteur_organisme_parametres_etapes_init_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisme_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtapeRecrutement"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
    utilisateur_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Utilisateur"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
}
