/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/recruteur/organisme/{organisme_uuid}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail d'un organisme */
        get: operations["recruteur_organisme_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruteur/organisme/{organisme_uuid}/parametres/etapes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des étapes de recrutement d'un organisme */
        get: operations["recruteur_organisme_parametres_etapes_list"];
        /** Modifier les étapes de recrutement d'un organisme */
        put: operations["recruteur_organisme_parametres_etapes_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruteur/organisme/{organisme_uuid}/parametres/etapes/init/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initialiser les étapes de recrutement par défaut d'un organisme */
        post: operations["recruteur_organisme_parametres_etapes_init_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruteur/organisme/{organisme_uuid}/recrutements/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liste des recrutements d'un organisme
         * @description Retourne la liste paginée des recrutements d'un organisme. Deux onglets disponibles via le paramètre `filtre` : `actifs` (recrutements en cours, défaut) et `archives` (offres archivées).
         */
        get: operations["recruteur_organisme_recrutements_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruteur/organisme/{organisme_uuid}/recrutements/{recrutement_uuid}/kanban/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Détail d'un recrutement — vue kanban */
        get: operations["recruteur_organisme_recrutements_kanban_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recruteur/organisme/{organisme_uuid}/recrutements/{recrutement_uuid}/liste/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Détail d'un recrutement — vue liste (paginée) */
        get: operations["recruteur_organisme_recrutements_liste_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/utilisateur/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail de l'utilisateur connecté */
        get: operations["utilisateur_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `AF` - AFRIQUE
         *     * `EU` - EUROPE
         *     * `AS` - ASIE
         *     * `AM` - AMERIQUE
         *     * `OC` - OCEANIE
         *     * `AN` - ANTARTIQUE
         * @enum {string}
         */
        AreaEnum: "AF" | "EU" | "AS" | "AM" | "OC" | "AN";
        Candidat: {
            /** Format: uuid */
            uuid: string;
            nom: string;
            prenom: string;
        };
        Candidature: {
            /** Format: uuid */
            uuid: string;
            /** Format: date-time */
            date_soumission: string;
            candidat: components["schemas"]["Candidat"];
        };
        CandidatureListe: {
            /** Format: uuid */
            uuid: string;
            /** Format: date-time */
            date_soumission: string;
            candidat: components["schemas"]["Candidat"];
            etape: components["schemas"]["EtapeRecrutementDetail"];
        };
        CandidaturesActives: {
            total: number | null;
            a_traiter: number | null;
            en_cours: number | null;
        };
        /**
         * @description * `ENTREE` - entree
         *     * `EN_COURS` - en_cours
         *     * `REFUS` - refus
         *     * `ACCEPTE` - accepte
         * @enum {string}
         */
        CategorieEnum: "ENTREE" | "EN_COURS" | "REFUS" | "ACCEPTE";
        /**
         * @description * `APLUS` - APLUS
         *     * `A` - A
         *     * `B` - B
         *     * `C` - C
         *     * `HORS_CATEGORIE` - HORS_CATEGORIE
         * @enum {string}
         */
        CategorieOffreEnum: "APLUS" | "A" | "B" | "C" | "HORS_CATEGORIE";
        EtapeRecrutement: {
            /** Format: uuid */
            etape_uuid: string;
            nom: string;
            categorie: components["schemas"]["CategorieEnum"];
        };
        EtapeRecrutementDetail: {
            /** Format: uuid */
            etape_uuid: string;
            nom: string;
            categorie: components["schemas"]["CategorieEnum"];
        };
        EtapeRecrutementDetailedCandidatures: {
            /** Format: uuid */
            etape_uuid: string;
            nom: string;
            categorie: components["schemas"]["CategorieEnum"];
            candidatures: components["schemas"]["Candidature"][];
        };
        GenericError: {
            error: string;
        };
        /**
         * @description * `CDD` - CDD
         *     * `CDI` - CDI
         *     * `PERMANENT` - Permanent
         *     * `VACATION` - Vacation
         *     * `STAGE` - Stage
         * @enum {string}
         */
        KindContratEnum: "CDD" | "CDI" | "PERMANENT" | "VACATION" | "STAGE";
        Localisation: {
            area: components["schemas"]["AreaEnum"];
            /** @description Code ISO Alpha-3 du pays (ex: FRA) */
            country: string;
            /** @description Code INSEE de la région (ex: 11) */
            region: string;
            /** @description Code INSEE du département (ex: 75) */
            department: string;
            label?: string | null;
            /** Format: double */
            latitude?: number | null;
            /** Format: double */
            longitude?: number | null;
        };
        /** @enum {unknown} */
        NullEnum: null;
        Organisme: {
            nom: string;
            siret: string;
        };
        OrganismeRecruteur: {
            nom: string;
            siret: string;
        };
        RecrutementActif: {
            /** Format: uuid */
            offer_id: string;
            intitule: string;
            reference_csp: string;
            type_contrat: (components["schemas"]["TypeContratEnum"] | components["schemas"]["NullEnum"]) | null;
            kind_contrat: (components["schemas"]["KindContratEnum"] | components["schemas"]["NullEnum"]) | null;
            /** Format: date-time */
            date_publication: string;
            responsables: components["schemas"]["Responsable"][];
            /** Format: date-time */
            derniere_activite: string;
            candidatures: components["schemas"]["CandidaturesActives"] | null;
        };
        RecrutementActifPage: {
            count: number;
            /** Format: uri */
            next: string | null;
            /** Format: uri */
            previous: string | null;
            results: components["schemas"]["RecrutementActif"][];
        };
        RecrutementDetailKanban: {
            /** Format: uuid */
            offer_id: string;
            intitule: string;
            /** Format: date-time */
            date_publication: string;
            localisation: components["schemas"]["Localisation"];
            organisme_recruteur: components["schemas"]["OrganismeRecruteur"];
            categorie_offre: components["schemas"]["CategorieOffreEnum"];
            etapes: components["schemas"]["EtapeRecrutementDetailedCandidatures"][];
        };
        RecrutementDetailListePage: {
            count: number;
            /** Format: uri */
            next: string | null;
            /** Format: uri */
            previous: string | null;
            results: components["schemas"]["CandidatureListe"][];
        };
        Responsable: {
            nom: string;
        };
        TokenError: {
            detail: string;
            code: string;
            messages: components["schemas"]["TokenErrorMessage"][];
        };
        TokenErrorMessage: {
            token_class: string;
            token_type: string;
            message: string;
        };
        /**
         * @description * `TITULAIRE_CONTRACTUEL` - TITULAIRE_CONTRACTUEL
         *     * `CONTRACTUELS` - CONTRACTUELS
         *     * `TERRITORIAL` - TERRITORIAL
         * @enum {string}
         */
        TypeContratEnum: "TITULAIRE_CONTRACTUEL" | "CONTRACTUELS" | "TERRITORIAL";
        UpdateEtapeRecrutement: {
            /** Format: uuid */
            etape_uuid?: string;
            nom: string;
            categorie: components["schemas"]["CategorieEnum"];
        };
        Utilisateur: {
            /** Format: email */
            email: string;
            prenom: string;
            nom: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    recruteur_organisme_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisme_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organisme"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
    recruteur_organisme_parametres_etapes_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisme_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtapeRecrutement"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
    recruteur_organisme_parametres_etapes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisme_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEtapeRecrutement"][];
                "application/x-www-form-urlencoded": components["schemas"]["UpdateEtapeRecrutement"][];
                "multipart/form-data": components["schemas"]["UpdateEtapeRecrutement"][];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtapeRecrutement"][];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
    recruteur_organisme_parametres_etapes_init_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisme_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtapeRecrutement"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
    recruteur_organisme_recrutements_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisme_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecrutementActifPage"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
    recruteur_organisme_recrutements_kanban_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisme_uuid: string;
                recrutement_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecrutementDetailKanban"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
    recruteur_organisme_recrutements_liste_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisme_uuid: string;
                recrutement_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecrutementDetailListePage"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
    utilisateur_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Utilisateur"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
        };
    };
}
