# Generated by Django 5.2.7 on 2025-11-19 10:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_rawcorps_alter_rawexamination_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDocument',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('raw_data', models.JSONField(verbose_name='RawDocument')),
                ('document_type', models.CharField(blank=True, choices=[('CORPS', 'CORPS'), ('GRADE', 'GRADE'), ('CONCOURS', 'CONCOURS')], max_length=10, null=True, verbose_name='Type de document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RawDocument',
                'verbose_name_plural': 'RawDocument',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameModel(
            old_name='RawExamination',
            new_name='LegifranceConcours',
        ),
        migrations.DeleteModel(
            name='RawCorps',
        ),
        migrations.AlterModelOptions(
            name='legifranceconcours',
            options={'ordering': ['-created_at'], 'verbose_name': 'RawConcours', 'verbose_name_plural': 'RawConcourss'},
        ),
    ]
