# Generated by Django 5.2.7 on 2025-12-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0007_vectorizeddocumentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpsmodel',
            name='category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
