# Generated by Django 5.2.7 on 2025-12-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0008_alter_corpsmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorizeddocumentmodel',
            name='document_type',
            field=models.CharField(choices=[('CORPS', 'CORPS'), ('GRADE', 'GRADE'), ('CONCOURS', 'CONCOURS')], db_index=True, default='CORPS', max_length=20),
            preserve_default=False,
        ),
    ]
