# Generated by Django 5.2.7 on 2025-12-08 17:06

from django.db import migrations


def populate_external_id(apps, schema_editor):
    """Populate external_id for existing documents."""
    RawDocument = apps.get_model('ingestion', 'RawDocument')

    for doc in RawDocument.objects.filter(external_id__isnull=True):
        if doc.document_type == 'CORPS':
            corps_id = doc.raw_data.get('corps_id')
            if corps_id:
                doc.external_id = str(corps_id)
                doc.save()
        elif doc.document_type == 'CONCOURS':
            nor_value = doc.raw_data.get('N° NOR')
            if nor_value:
                doc.external_id = str(nor_value)
                doc.save()
        else:
            doc.external_id = f"doc_{doc.id}"
            doc.save()


def reverse_populate_external_id(apps, schema_editor):
    """Reverse migration - clear external_id."""
    RawDocument = apps.get_model('ingestion', 'RawDocument')
    RawDocument.objects.update(external_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0011_add_external_id_to_rawdocument'),
    ]

    operations = [
        migrations.RunPython(populate_external_id, reverse_populate_external_id),
    ]
