# Generated by Django 5.2.7 on 2025-12-15 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0012_populate_external_id_for_existing_documents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CorpsModel',
        ),
        migrations.DeleteModel(
            name='VectorizedDocumentModel',
        ),
    ]
