# Generated by Django 5.2.10 on 2026-01-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0013_delete_corpsmodel_delete_vectorizeddocumentmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawdocument",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CORPS", "CORPS"),
                    ("GRADE", "GRADE"),
                    ("CONCOURS", "CONCOURS"),
                    ("CONCOURS_LAW", "CONCOURS_LAW"),
                    ("CONCOURS_LAW_DETAILS", "CONCOURS_LAW_DETAILS"),
                    ("OFFERS", "OFFERS"),
                ],
                max_length=25,
                null=True,
                verbose_name="Type de document",
            ),
        ),
    ]
