# Generated by Django 6.0.2 on 2026-02-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0015_alter_rawdocument_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawdocument",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
