# Generated by Django 6.0.3 on 2026-03-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0018_rawdocument_processed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawdocument",
            name="processing",
            field=models.BooleanField(default=False),
        ),
    ]
