# Generated by Django 6.0.4 on 2026-04-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0019_rawdocument_processing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawdocument",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CORPS", "CORPS"),
                    ("GRADE", "GRADE"),
                    ("CONCOURS", "CONCOURS"),
                    ("OFFERS", "OFFERS"),
                    ("METIERS", "METIERS"),
                ],
                max_length=25,
                null=True,
                verbose_name="Type de document",
            ),
        ),
    ]
