# Generated by Django 5.2.7 on 2025-12-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVMetadataModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('extracted_text', models.JSONField()),
                ('search_query', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'CV Metadata',
                'verbose_name_plural': 'CV Metadata',
                'db_table': 'cv_metadata',
            },
        ),
    ]
