# Generated by Django 5.2.10 on 2026-02-02 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvmetadatamodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("completed", "completed"),
                    ("failed", "failed"),
                ],
                default="pending",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cvmetadatamodel",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cvmetadatamodel",
            name="extracted_text",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cvmetadatamodel",
            name="search_query",
            field=models.TextField(blank=True, null=True),
        ),
    ]
