import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { argv, exit } from 'node:process'

const SRC = new URL('../src', import.meta.url).pathname
const RI_DIR = new URL('../node_modules/@iconify-icons/ri', import.meta.url).pathname
const CUSTOM = join(SRC, 'app/icons.custom.ts')
const TARGET = join(SRC, 'app/icons.generated.ts')
const ICON_PATTERN = /\bri:[a-z0-9]+(?:-[a-z0-9]+)*\b/g
const CHECK = argv.includes('--check')

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name)
    if (statSync(path).isDirectory())
      return walk(path)
    return /\.(?:vue|ts)$/.test(name) ? [path] : []
  })
}

const custom = new Set(
  [...readFileSync(CUSTOM, 'utf8').matchAll(/addIcon\('([^']+)'/g)].map(m => m[1]),
)

const used = new Map()
for (const file of walk(SRC)) {
  if (file === TARGET || file === CUSTOM)
    continue
  for (const match of readFileSync(file, 'utf8').matchAll(ICON_PATTERN)) {
    if (!used.has(match[0]))
      used.set(match[0], [])
    used.get(match[0]).push(file.replace(`${SRC}/`, ''))
  }
}

const names = [...used.keys()].filter(name => !custom.has(name)).sort()

const unknown = names.filter(name => !existsSync(join(RI_DIR, `${name.slice(3)}.js`)))
if (unknown.length > 0) {
  console.error(`✗ ${unknown.length} icon(s) not found in @iconify-icons/ri (typo? or add to icons.custom.ts):`)
  for (const name of unknown)
    console.error(`  ${name}  (${[...new Set(used.get(name))].slice(0, 3).join(', ')})`)
  exit(1)
}

const unusedCustom = [...custom].filter(name => !used.has(name))
if (unusedCustom.length > 0)
  console.warn(`ℹ ${unusedCustom.length} custom icon(s) unused: ${unusedCustom.join(', ')}`)

function importName(name) {
  return `ri${name.slice(3).replace(/(?:^|-)([a-z0-9])/g, (_, c) => c.toUpperCase())}`
}

const content = `${[
  '// Generated by scripts/build-icons.mjs from the ri:* names used in src/.',
  '// Do not edit: run `pnpm icons` to regenerate.',
  ...names.map(name => `import ${importName(name)} from '@iconify-icons/ri/${name.slice(3)}'`),
  'import { addIcon } from \'@iconify/vue\'',
  '',
  ...names.map(name => `addIcon('${name}', ${importName(name)})`),
].join('\n')}\n`

if (CHECK) {
  const current = existsSync(TARGET) ? readFileSync(TARGET, 'utf8') : ''
  if (current !== content) {
    console.error('✗ src/app/icons.generated.ts is out of date, run: pnpm icons')
    exit(1)
  }
  console.log(`✓ ${names.length + custom.size} icons, registry up to date.`)
}
else {
  writeFileSync(TARGET, content)
  console.log(`✓ wrote ${names.length} icons to src/app/icons.generated.ts (+${custom.size} custom).`)
}
