from typing import Protocol

from domain.identite.entities.utilisateurs import Utilisateur


class IUtilisateurRepository(Protocol):
    def get_by_entity_id(self, entity_id) -> Utilisateur: ...
    def get_by_email(self, email: str) -> Utilisateur: ...
    def create(self, utilisateur: Utilisateur) -> Utilisateur: ...
