# Generated by Django 6.0.6 on 2026-06-15 14:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "candidate",
            "0002_cvmetadatamodel_status_cvmetadatamodel_updated_at_and_more",
        ),
        ("referentiel", "0034_remove_apilogmodel"),
        ("users", "0007_merge_20260612_1624"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidatureModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("initial", "initial"),
                            ("soumise", "soumise"),
                            ("retiree", "retiree"),
                        ],
                        default="initial",
                        max_length=20,
                    ),
                ),
                ("documents", models.JSONField(blank=True, null=True)),
                ("soumise_le", models.DateTimeField(blank=True, null=True)),
                ("mise_a_jour_le", models.DateTimeField(blank=True, null=True)),
                (
                    "candidat",
                    models.ForeignKey(
                        db_column="candidat_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidatures",
                        to="users.profilcandidatmodel",
                        to_field="utilisateur_id",
                    ),
                ),
                (
                    "offre",
                    models.ForeignKey(
                        db_column="offre_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidatures",
                        to="referentiel.offermodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidature",
                "verbose_name_plural": "Candidatures",
                "db_table": "candidature",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("candidat_id", "offre_id"),
                        name="unique_candidature_candidat_offre",
                    )
                ],
            },
        ),
    ]
