# Generated by Django 6.0.6 on 2026-06-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "candidate",
            "0002_cvmetadatamodel_status_cvmetadatamodel_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvmetadatamodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="cvmetadatamodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
