# Generated by Django 6.0.6 on 2026-06-16 09:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0003_alter_cvmetadatamodel_created_at_and_more"),
        ("referentiel", "0035_restore_offers_primary_key"),
        ("users", "0007_merge_20260612_1624"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidatureModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("initial", "initial"),
                            ("soumise", "soumise"),
                            ("retiree", "retiree"),
                        ],
                        default="initial",
                        max_length=20,
                    ),
                ),
                ("documents", models.JSONField(blank=True, null=True)),
                (
                    "candidat",
                    models.ForeignKey(
                        db_column="candidat_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidatures",
                        to="users.profilcandidatmodel",
                        to_field="utilisateur_id",
                    ),
                ),
                (
                    "offre",
                    models.ForeignKey(
                        db_column="offre_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidatures",
                        to="referentiel.offermodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidature",
                "verbose_name_plural": "Candidatures",
                "db_table": "candidature",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("candidat_id", "offre_id"),
                        name="unique_candidature_candidat_offre",
                    )
                ],
            },
        ),
    ]
