# Generated by Django 6.0.6 on 2026-07-08 10:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_fix_cv_metadata_id_index'),
        ('recruteur', '0003_recrutement_etapes'),
        ('users', '0007_merge_20260612_1624'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candidaturemodel',
            name='unique_candidature_candidat_offre',
        ),
        migrations.AddField(
            model_name='candidaturemodel',
            name='etape',
            field=models.ForeignKey(db_column='etape_id', help_text="Étape courante du recrutement (par défaut, l'étape ENTREE du recrutement correspondant à l'offre).", on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='recruteur.etapemodel'),
        ),
        migrations.AlterField(
            model_name='candidaturemodel',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='candidaturemodel',
            constraint=models.UniqueConstraint(fields=('candidat_id', 'etape_id'), name='unique_candidature_candidat_etape'),
        ),
        migrations.RemoveField(
            model_name='candidaturemodel',
            name='offre',
        ),
    ]
