# Generated by Django 6.0.7 on 2026-08-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_remove_candidaturemodel_unique_candidature_candidat_offre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaturemodel',
            name='updated_by_candidate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidaturemodel',
            name='updated_by_recruteur',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
