# Generated by Django 6.1 on 2026-08-19 14:05

import django.db.models.deletion
from django.db import migrations, models


def _drop_pattern_ops_index_sql(table: str, column: str) -> str:
    return f"""
        DO $$
        DECLARE
            idx_name text;
        BEGIN
            SELECT ic.relname INTO idx_name
            FROM pg_index ix
            JOIN pg_class ic ON ic.oid = ix.indexrelid
            JOIN pg_class tc ON tc.oid = ix.indrelid
            JOIN pg_attribute a ON a.attrelid = tc.oid AND a.attnum = ANY(ix.indkey)
            JOIN pg_opclass oc ON oc.oid = ANY(ix.indclass)
            WHERE tc.relname = '{table}'
              AND a.attname = '{column}'
              AND oc.opcname IN ('varchar_pattern_ops', 'text_pattern_ops')
            LIMIT 1;

            IF idx_name IS NOT NULL THEN
                EXECUTE format('DROP INDEX IF EXISTS %I', idx_name);
            END IF;
        END $$;
    """  # noqa: S608


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0007_candidaturemodel_updated_by_candidate_and_more"),
        ("users", "0008_alter_usermodel_username"),
    ]

    operations = [
        migrations.RunSQL(
            _drop_pattern_ops_index_sql("candidature", "candidat_id"),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="candidaturemodel",
            name="candidat",
            field=models.ForeignKey(
                db_column="candidat_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="candidatures",
                to="users.profilcandidatmodel",
                to_field="utilisateur_id",
            ),
        ),
    ]
