# Generated by Django 6.1 on 2026-08-19 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0008_alter_candidaturemodel_candidat"),
        ("users", "0008_alter_usermodel_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidaturemodel",
            name="candidat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="candidatures",
                to="users.profilcandidatmodel",
                to_field="utilisateur_id",
            ),
        ),
    ]
