# Generated by Django 6.1.1 on 2026-09-16 19:58

import django.db.models.deletion
import infrastructure.django_apps.candidate.models.document
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0010_candidaturemodel_motif_refus"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("cv", "CV"),
                            ("lettre_motivation", "Lettre de motivation"),
                            ("piece_justificative", "Pièce justificative"),
                            ("autre", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        max_length=512,
                        storage=infrastructure.django_apps.candidate.models.document.candidature_documents_storage,
                        upload_to=infrastructure.django_apps.candidate.models.document.document_upload_to,
                    ),
                ),
                ("nom_original", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("taille", models.PositiveIntegerField()),
                (
                    "candidature",
                    models.ForeignKey(
                        db_column="candidature_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents_uploaded",
                        to="candidate.candidaturemodel",
                    ),
                ),
                (
                    "depose_par",
                    models.ForeignKey(
                        db_column="depose_par_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents_deposes",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document de candidature",
                "verbose_name_plural": "Documents de candidature",
                "db_table": "candidature_document",
            },
        ),
    ]
