from typing import List, Protocol
from uuid import UUID

from domain.entities.offer import Offer
from domain.repositories.document_repository_interface import IUpsertResult


class IOffersRepository(Protocol):
    def upsert_batch(self, offers_list: List[Offer]) -> IUpsertResult: ...

    def find_by_id(self, offer_id: UUID) -> Offer: ...

    def find_by_ids(self, offer_ids: List[UUID]) -> List[Offer]: ...

    def find_by_external_id(self, external_id: str) -> Offer: ...

    def get_pending_processing(self, limit: int = 1000) -> List[Offer]: ...

    def mark_as_processed(self, offers_list: List[Offer]) -> int: ...

    def mark_as_pending(self, offers_list: List[Offer]) -> int: ...
