name: Dev

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [ opened, synchronize, reopened, edited ]
    paths:
      - "dev/**"

permissions:
  contents: read

jobs:
  build-dev:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dev
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.17"
          enable-cache: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "./dev/.python-version"
      - name: Install dev tools
        run: uv sync --locked --all-extras --dev

  build-docker-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build dev Docker image
        run: bin/compose build dev
