name: Dev

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [ opened, synchronize, reopened, edited ]
    paths:
      - "dev/**"
      - "mise.toml"
      - ".github/workflows/dev.yml"
      - ".github/actions/**"

permissions:
  contents: read

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-mise
      - name: Install dev tools
        run: mise run dev:install
