name: Notebook

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [ opened, synchronize, reopened, edited ]
    #trigger this workflow if files have changed in notebook
    paths:
      - "src/notebook/**"
      - "mise.toml"
      - ".github/workflows/notebook.yml"
      - ".github/actions/**"

permissions:
  contents: read

jobs:
  build-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-mise
      - name: Install the project
        run: mise run notebook:install
