name: Notebook Pages

on:
  push:
    branches: ["main"]
    paths:
      - "docs/notebook/**"
      - ".github/workflows/notebook_pages.yml"

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: gh-pages-deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Deploy notebooks to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/notebook
          target-folder: notebook
          force: false
