name: OCR

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, edited]
    paths:
      - "src/ocr/**"

permissions:
  contents: read

jobs:
  build-ocr:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-uv-python
        with:
          service-path: src/ocr
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils tesseract-ocr tesseract-ocr-fra

  lint-ocr:
    needs: build-ocr
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/ocr
    steps:
      - uses: ./.github/actions/setup-uv-python
        with:
          service-path: src/ocr
      - name: Lint with Ruff
        run: uv run ruff check .
      - name: Lint format with Ruff
        run: uv run ruff format --check .
      - name: Lint with MyPy
        run: uv run mypy .

  test-ocr:
    needs: build-ocr
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/ocr
    env:
      API_KEY: test-api-key-for-development
    steps:
      - uses: ./.github/actions/setup-uv-python
        with:
          service-path: src/ocr
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils tesseract-ocr tesseract-ocr-fra
      - name: Test with pytest
        run: uv run pytest .
